arch/X86/X86DisassemblerDecoder.c

x86: add more valid instructions for LOCK prefix

---

bindings/python/setup.py

* Config distutils setup to automate copying shared library to Python library directory
* Fixbug: prevent make.sh running on windows system

Finished setup script for *unix system

---

bindings/python/pyx/ccapstone.pyx

Hello,
I've an error when compiling the bindings: the name `csh` conflicts with `typedef csh` in `capstone.h`:
bindings/python/pyx/ccapstone.pyx_cython_generated.cc:446:7: error: declaration of 'csh __pyx_obj_9ccapstone_Cs::csh' [-fpermissive]
In file included from bindings/python/pyx/ccapstone.pyx_cython_generated.cc:230:0:
capstone.h:48:16: error: changes meaning of 'csh' from 'typedef size_t csh' [-fpermissive]
cc1plus: error: unrecognized command line option "-Wno-implicit-fallthrough" [-Werror]
cc1plus: all warnings being treated as errors
This common error is described on [stackoverflow](http://stackoverflow.com/questions/12187549/typedef-changes-meaning) [posts](http://stackoverflow.com/questions/15191127/changes-meaning-from-typedef).
The solution is to rename to `_csh` as it is …

python bindings: rename member struct to _csh to avoid conflict with typedef csh

---

arch/AArch64/AArch64Mapping.c

Hi Mr. Quynh,
I have just added some instructions into insn_ops array in https://github.com/aquynh/capstone/blob/next/arch/AArch64/AArch64Mapping.c
Please check it!
Thanks!

Add instructions into insn_ops

---

.gitignore
xcode/Capstone.xcodeproj/project.pbxproj

As requested.
Should I also do it in other branches (next, v2, v3)?

Renaming inttypes.h -> myinttypes.h

---

arch/Sparc/SparcInstPrinter.c

Calls & conditional branches were not decoded properly when using negative displacements.
It might still fail in some cases because sometimes MI->csh->detail is not defined and I cannot figure out if its a conditional branch with prediction or not, so I cannot calculate the displacement size properly...

Sparc conditional branches displacement fix

---

suite/arm/test_arm_regression.c

use the correct include location

---

CMakeLists.txt

Include common headers in cmake projects.

---

xcode/Capstone.xcodeproj/project.pbxproj
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

Added test_customized_mnem file and target to Xcode project

---

msvc/capstone.sln
msvc/test_iter/test_iter.vcxproj

I added the test_iter.c inside a separate VC project & added that one to the solution file to be built along with the others.
Cheers,
0vercl0k

Adding test_iter to the MSVC solution

---

msvc/capstone.sln
msvc/test_customized_mnem/test_customized_mnem.vcxproj
msvc/test_iter/test_iter.vcxproj

I added test_iter.c & test_customized_mnem.c inside their respective VC projects & added the project to the main MSVC solution.
Cheers,
0vercl0k

Adding test_iter & test_customized_mnem to the msvc solution

---

arch/PowerPC/PPCInstPrinter.c

Fixes https://github.com/aquynh/capstone/issues/377

Fix building by MSVC 2010 lacking inttypes.h

---

bindings/python/capstone/__init__.py

Issue and PoC: https://github.com/aquynh/capstone/issues/398

fix issue #398 (Python binding no deep copy of detail pointer)

---

xcode/Capstone.xcodeproj/project.pbxproj

Pretty sure you asked for this a while ago, I completely forgot about it. Better late than never?

Renamed test.c to test_basic.c in Xcode project

---

bindings/const_generator.py
bindings/java/capstone/Arm64_const.java
bindings/ocaml/arm64_const.ml

Fix the const generator output.
It didnt like the #define's present in the x86 header.

Const generator

---

suite/regress.py

Adding tests for #470, as requested in #471.

Add GDT/IDT handling instructions to tests

---

arch/M68K/M68Kdasm.c

Implement reentrance support by using an internal private structure
m68k_info.
Only g_instruction_table is still global as it's read only, and
will be initialized once, by the first instance.
Related to issue #494
```
typedef struct m68k_info {
MCInst *inst;
uint pc;        /* program counter */
uint ir;        /* instruction register */
uint type;
unsigned int address_mask; /* Address mask to simulate address lines */
} m68k_info;
```
Signed-off-by: Nicolas PLANEL <nplanel@gmail.com>

[M68K] Multi instance support, reentrance support

---

xcode/Capstone.xcodeproj/project.pbxproj

This PR updates the Xcode project targets to support M68k.

Xcode project update to add support for M68k

---

arch/X86/X86Disassembler.c

fix:prefix 0x67 missed.

---

arch/M68K/M68KDisassembler.c
arch/M68K/M68KDisassembler.h
arch/M68K/M68KModule.c
bindings/python/test_m68k.py

[M68K] fixup read/peak() address_line_mask
[M68K] fixup increment pc only if the instruction_is_valid()
[M68K] cleanup : move the initialization of m68k_info
[M68K] Add boundary checker
[binding][python] print the string value of CsError
Related to issue #494

fixup for Radare

---

arch/X86/X86Mapping.c

LOOP, LOOPE and LOOPNE are basically conditional branches http://x86.renejeschke.de/html/file_module_x86_id_161.html

LOOP* instructions are conditional branches

---

arch/X86/X86Mapping.c

Sorry, since the file is very big I didn't realize there was a 2nd list.

LOOP* branch fix for full x64 instructions

---

MCInst.h
cs.c

Pair of small commits that aim to improve code quality a little.

Code cleanup

---

xcode/Capstone.xcodeproj/project.pbxproj
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Dynamic Library.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Framework.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Static Library.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
xcode/CapstoneFramework/Info.plist

This PR just updates the Xcode project settings to the Xcode 7 "recommended settings" to clear warnings.

Updated to recommended settings (per Xcode 7)

---

Makefile
config.mk
cs.c
make.sh

See https://github.com/aquynh/capstone/issues/526.

Support of xnu memory allocator

---

suite/regress/invalid_read_in_print_operand.c

Add crash case: "Invalid read of size 4" in printOperand(…)

---

.travis.yml
Makefile
README.md

The travis tests should pass with this PR.

Fix library install for tests

---

bindings/python/MANIFEST.in

Missed adding C dependencies in sdist.

Added a missed dependency to MANIFEST.in.

---

arch/AArch64/AArch64InstPrinter.c

fix oob write in arch/AArch64/AArch64InstPrinter.c

---

contrib/objdump/objdump-m68k.py
include/capstone/m68k.h

[python][contrib][objdump] fixup op.register_bits access
[M68K] typo on m68k_address_mode private struct

Fixup.20160411

---

include/capstone/x86.h
tests/test_x86.c

This addresses https://github.com/aquynh/capstone/issues/648

Remove never used cs_x86_op::fp

---

HACK.TXT
contrib/cs_driver/cs_driver/cs_driver.c
cs.c
include/platform.h
tests/README
tests/test_winkernel.cpp

This update is to synchronize the master to changes I made at #680. 
While porting to the next branch, I found some documentation and comment errors, places to clean up for consistency and suppressing warnings with warning level 4 and prefast. Those update should have no effects on behaviour of code.

edit documents and comments

---

bindings/python/capstone/__init__.py
bindings/python/capstone/arm.py
bindings/python/capstone/arm64.py
bindings/python/capstone/m68k.py
bindings/python/capstone/mips.py
bindings/python/capstone/ppc.py
bindings/python/capstone/sparc.py
bindings/python/capstone/systemz.py
bindings/python/capstone/x86.py
bindings/python/capstone/xcore.py

Apply changes changes from !697 on next branch

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aquynh/capstone/715)

ignore build directories for CMake

---

arch/AArch64/AArch64MappingInsn.inc

Fix group information and branch information for [BL](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/BL.html), [BLR](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0802a/BLR.html)

Fix BL, BLR group information

---

include/arm.h

fix annotation.

---

suite/arm/test_arm_regression.c

https://msdn.microsoft.com/en-us/library/2ts7cx93.aspx#Anchor_3

fixed issue #726 (snprintf undefined in test_arm_regression)

---

.gitignore
COMPILE_MSVC.TXT
HACK.TXT
arch/AArch64/AArch64BaseInfo.c
arch/M68K/M68KInstPrinter.c
arch/Sparc/SparcInstPrinter.c
arch/X86/X86Mapping.c
arch/XCore/XCoreInstPrinter.c
contrib/cs_driver/cs_driver/cs_driver.c
cs.c
docs/README
include/capstone/x86.h
tests/test_winkernel.cpp
windows/winkernel_mm.c
windows/winkernel_mm.h

3730e20 and bc954d0 were added on the top of PR #779

PR #779 plus more warning suppression and compile error fix

---

arch/X86/X86Mapping.c

See https://github.com/aquynh/capstone/pull/797 (it was done first on next branch)

Add X86_REG_EFLAGS for X86_STC and X86_STD

---

arch/X86/X86MappingInsn.inc
arch/X86/X86MappingInsn_reduce.inc

See https://github.com/aquynh/capstone/pull/800

Add X86_REG_EFLAGS to X86_CLC, X86_CLD, X86_CMC

---

.gitignore
suite/regress.py

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/aquynh/capstone/830)

added regression test for #702 + ignore build directories

---

arch/M68K/M68KDisassembler.c
arch/M68K/M68KInstPrinter.c
bindings/python/capstone/m68k.py
include/capstone/m68k.h

(M68k) make displacements signed

---

bindings/python/setup.py

Add python prebuilt directory

---

arch/ARM/ARMInstPrinter.c

fix compiling error in MS VS2015

---

CMakeLists.txt

credit goes to Theo. (Theodore Papadopoulo Theodore.Papadopoulo at inria.fr https://cmake.org/pipermail/cmake/2013-July/055374.html)

detect 64bit library location. compatibility for 64bit systems.

---

arch/AArch64/AArch64Mapping.c
arch/ARM/ARMMapping.c
arch/M68K/M68KInstPrinter.c
arch/Mips/MipsMapping.c
arch/X86/X86Mapping.c

Add name to relative branch group in supported architectures.

---

Makefile
make.sh

Fixes #1003 
Please be extra careful when reviewing as I never wrote a Makefile.
I did not make the logic too complex, so in theory you can specify this flag for non osx builds. Hope this is ok.

Add posibility to disable universal build for osx.

---

bindings/python/test_x86.py

is equal to the code in https://github.com/aquynh/capstone/blob/next/tests/test_x86.c

retrieve and print "status register updates" info

---

arch/X86/X86DisassemblerDecoder.c

Fix pp field in readPrefix for VEX3 and EVEX (#1015)

---

xcode/Capstone.xcodeproj/project.pbxproj
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Dynamic Library.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Framework.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Static Library.xcscheme
xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme

Updated Xcode project for Xcode 9.1

---

bindings/java/capstone/X86.java

Fix type of eflags in java binding

---

bindings/python/README.txt
bindings/python/capstone/__init__.py
bindings/python/setup.py

Port library environment variable from unicorn

---

arch/AArch64/AArch64Module.c
arch/ARM/ARMModule.c
arch/Mips/MipsModule.c
arch/PowerPC/PPCModule.c
arch/Sparc/SparcModule.c
arch/SystemZ/SystemZModule.c
arch/X86/X86Module.c
arch/XCore/XCoreModule.c
cs.c
cs_priv.h

prefix cs_ to global variables to avoid link problems

---

SStream.c
arch/SystemZ/SystemZInstPrinter.c

Adding to the fixes submitted in commit 5b55115c425b4b08225ea7814070da793d442109

Fixing #1060

---

SStream.c
arch/SystemZ/SystemZInstPrinter.c

Updating fix from commit 5b55115c425b4b08225ea7814070da793d442109

Fixing #1062

---

SStream.c
arch/Sparc/SparcInstPrinter.c

Updating the fix provided in commit 5b55115c425b4b08225ea7814070da793d442109

Fixing #1061

---

Makefile
make.sh

simplifies builds, prevents overriding of options

Move functionality from make.sh to Makefile

---

CMakeLists.txt
suite/fuzz/fuzz_disasm.c
suite/fuzz/fuzz_disasm.options
suite/fuzz/onefile.c

@aquynh as you asked, this is the same as #1145 but for master branch

Integrate capstone with oss-fuzz

---

CREDITS.TXT

Adds Philippe Antoine (Catena cyber) to credits

---

LEB128.h
arch/AArch64/AArch64AddressingModes.h
arch/AArch64/AArch64Disassembler.c
arch/ARM/ARMAddressingModes.h
arch/ARM/ARMDisassembler.c
arch/Mips/MipsDisassembler.c
arch/PowerPC/PPCDisassembler.c
arch/PowerPC/PPCInstPrinter.c
arch/Sparc/SparcDisassembler.c
arch/XCore/XCoreDisassembler.c

Found using oss-fuzz-fuzz
Use multiply, or promote to unsigned integer of right size before shifting

Undefined shifts

---

MCInst.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8681

operands are invalid at initialisation

---

arch/AArch64/AArch64InstPrinter.c
arch/PowerPC/PPCInstPrinter.c

Use multiply instead
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8678
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8683

Fix undefined shifts

---

SStream.c

As #1155 for master branch this time

Print right hex value for MIN_INT

---

arch/ARM/ARMInstPrinter.c

Found debugging https://github.com/trailofbits/manticore/issues/514 (and not using fuzzing)

Fix ARM operand subtracted field

---

suite/fuzz/fuzz_disasm.c

See https://github.com/google/oss-fuzz/pull/1457#issuecomment-394858595

Adds a size limit for inputs to fuzz target

---

arch/EVM/EVMDisassembler.c
arch/EVM/EVMMapping.c
arch/EVM/EVMMappingInsn.inc

Sets id to instruction
Completes missing set and enforces number of instructions

EVM fuzz fixes

---

arch/SystemZ/SystemZInstPrinter.c

SystemZ MIN_INT right print

---

suite/fuzz/fuzz_disasm.c
suite/test_corpus.py

Builds a test corpus for fuzzing

---

bindings/python/capstone/__init__.py

Better error reporting for python binding

---

arch/TMS320C64x/TMS320C64xInstPrinter.c

WIP: arch/TMS320C64x: fix underflow

---

suite/fuzz/onefile.c

As asked by @kcc in https://github.com/aquynh/capstone/pull/1150#pullrequestreview-147055377

Avoids memory leak with fuzz driver

---

include/capstone/m680x.h

Fix typo: combined.

---

Makefile

Recognize MSYS compiler as MINGW compiler

---

bindings/README

Added link to D bindings (fixes #1280)

Updated bindings README

---

.travis.yml
Makefile
suite/fuzz/Makefile
suite/fuzz/drivermc.c
tests/Makefile

This is my first time with travis, so it may need review (the makefiles as well)
+ there is a new so-called fuzz driver which converts the files in suite/MC to a binary buffer for the fuzz target
But it has been working with me

Continuous integration for fuzzing

---

.travis.yml
Makefile
suite/fuzz/Makefile
suite/fuzz/driverbin.c
suite/fuzz/fuzz_diff.c
suite/fuzz/fuzz_llvm.cpp

As recommended by @kcc in
https://github.com/google/oss-fuzz/issues/1989#issuecomment-443368973
The longest part for this addition is the unzipping
I am unsure about where to put the corpus :
- I chose on my web site, but it is not guaranteed to last forever
- on GitHub with the source code, but it will overload the versioning (155M of binary files)
- from Google Cloud, but travis will have to authenticate itself...
Last note : I wrote a new driver for the fuzz harness which fuzzes all the files in a directory passed as the only argument

Use whole corpus for regression testing

---

Makefile

Test fuzz whole corpus only if present

---

cstool/Makefile
tests/Makefile

Following in the steps of #1290

Normalize IS_MINGW checks (and include MSYS, like main Makefile)

---

.travis.yml

Travis unzip quieter

---

bindings/python/capstone/__init__.py
bindings/python/test_skipdata.py

This fixes #1316.
Also includes enhancements I proposed in the same issue.
If required I can create a separate PR with just the fix.

Fix skipdata setup

---

MCInst.h
arch/AArch64/AArch64Disassembler.c
arch/M68K/M68KDisassembler.c
arch/M68K/M68KInstPrinter.c
arch/M68K/M68KInstPrinter.h
arch/Mips/MipsDisassembler.c
arch/Mips/MipsDisassembler.h
arch/PowerPC/PPCDisassembler.c
arch/Sparc/SparcDisassembler.c
arch/SystemZ/SystemZDisassembler.c
arch/TMS320C64x/TMS320C64xDisassembler.c
arch/X86/X86IntelInstPrinter.c
arch/XCore/XCoreDisassembler.c

Did a new pr - seemed easier this way

Fix missing-prototypes warnings

---

HACK.TXT
include/capstone/capstone.h

(and fixing a comment)
See #1307

Doc about adding an architecture

---

suite/fuzz/fuzz_disasm.c

Let's not forget to fuzz new architectures
Otherwise, I will add a Travis test for it

Fuzzing new wasm architecture

---

Makefile
suite/fuzz/driverbin.c

Bash logical or for travis failure

---

arch/M68K/M68KDisassembler.c

Fixed m68k has wrong type of read_imm_64

---

arch/WASM/WASMDisassembler.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12956

Fix undefined shift in WASM disassembler

---

arch/TMS320C64x/TMS320C64xDisassembler.c

There were more to do from #1382

Fixes more undefined left shift of negative values

---

bindings/python/capstone/__init__.py

For the peace and tranquility of the earth.

For the benefit of mankind.

---

HACK.TXT
suite/fuzz/fuzz_disasm.c
suite/test_corpus.py

cc @david942j 
We had forgotten about corpus generation from MC files

Adds corpus generation for bpf architecture

---

suite/fuzz/fuzz_disasm.c

Fuzz more modes and ATT syntax

---

arch/RISCV/RISCVGenAsmWriter.inc

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13686

Fix memory leak in RISC V

---

make.sh

Use parameter expansion modifiers instead of manual tests.
Tested on Ubuntu 18.04 and FreeBSD 11

Make install.sh more idomatic

---

CMakeLists.txt
arch/RISCV/RISCVGenAsmWriter.inc
contrib/riscv_update/0010-fix-riscvgenasmwiter.inc-memory-leak.patch

Related with [#1424](https://github.com/aquynh/capstone/pull/1424) and [#1434](https://github.com/aquynh/capstone/pull/1434)

add riscv cmake support & using static array contain temp string for riscv

---

arch/M680X/M680XDisassembler.c

- Also improved address range check.
- Added comments for maintainers.

M680X: Remove warnings in msvc.

---

arch/AArch64/AArch64InstPrinter.c

Found by oss-fuzz :
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14174
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14175
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14178

Aarch64 set operand in printSVERegOp

---

.editorconfig

Add editorconfig to maintain consistent style
EditorConfig should help us maintain consistent style across different editors. Many editors have native support; others have plugins.
Website: https://editorconfig.org/

Add Editorconfig to help maintain consistent style across editors

---

.editorconfig

EditorConfig should help us maintain consistent style across different
editors. Many editors have native support; others have plugins.
Website: https://editorconfig.org/

Add editorconfig to maintain consistent style (#1486)

---

CMakeLists.txt
COMPILE_CMAKE.TXT
arch/RISCV/RISCVBaseInfo.h
arch/RISCV/RISCVDisassembler.c
arch/RISCV/RISCVGenAsmWriter.inc
arch/RISCV/RISCVGenDisassemblerTables.inc
arch/RISCV/RISCVInstPrinter.c
make.sh

[RISCV] Use CS_ASSERT

---

.travis.yml
README.md
suite/fuzz/Makefile
suite/fuzz/README.md
suite/fuzz/fuzzit.sh
suite/fuzz/fuzzitid.txt

Fuzzit is a continuous fuzzing platform
see https://fuzzit.dev/
This PR adds to Travis a step calling Fuzzit, simply uploading built fuzzer to the platform where the fuzzing will take place.
This PR adds also a more generic README about fuzzing

Fuzzit integration

---

README.md

Add missing bracket in top-level README.md file

---

COMPILE_CMAKE.TXT

Correct supported archs description - fix TMS320C64X and EVM lines.
Additionally remove some tariling spaces.

Update COMPILE_CMAKE.TXT file

---

arch/AArch64/AArch64Mapping.c
arch/AArch64/AArch64MappingInsn.inc
include/capstone/arm64.h

Hi,
I've added the group `ARM64_GRP_PAC` for grouping instructions relative to [PAC](https://www.qualcomm.com/media/documents/files/whitepaper-pointer-authentication-on-armv8-3.pdf).
Here is the list of the instructions I added to this new group:
* [ARM64_INS_AUTDA (AUTDA), ARM64_INS_AUTDZA (AUTDZA)](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0801g/ycn1476202675817.html) 
* [ARM64_INS_AUTDB (AUTDB), ARM64_INS_AUTDZB (AUTDZB)](http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0801g/epx1476202676637.html)
* [ARM64_INS_AUTIA (AUTIA), ARM64_INS_AUTIA1716 (AUTIA1716), ARM64_INS_AUTIASP (AUTIASP), ARM64_INS_AUTIZA (AUTIZA), ARM64_INS_AUTIAZ (AUTIAZ)](http://infocenter.arm.com/help/topic/com.arm.doc.dui0801g/rmi1476202677017.html)
* [ARM64_INS_AUTIB (AUTIB), …

Add ARM64_GRP_PAC group for Pointer Authentication

---

Makefile

Missing condition on CAPSTONE_BUILD_CORE_ONLY in Makefile

---

arch/M68K/M68KDisassembler.c

M68K: fix MOVEC operand transfer direction

---

MCInst.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14912

MCInst: fix uninitialized value in operand value

---

arch/PowerPC/PPCDisassembler.c

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236

ppc: fix registers overflow

---

CMakeLists.txt

Update cmake_minimum_required to version 2.8.12

---

README.md

See https://google.github.io/oss-fuzz/getting-started/new-project-guide/#status-badge

Adds oss-fuzz badge

---

README.md

Refers users to the next branch
Helps bring #1781 to a close

readme: mention master branch deprecation

---

MCInst.c
arch/X86/X86DisassemblerDecoder.c
cs.c

This PR is authored by @radare and tested against https://github.com/athre0z/disas-bench and valgrind.

Some performance improvement

---

bindings/python/capstone/__init__.py
bindings/python/capstone/x86.py
bindings/python/test_x86.py

Pull request addressing issue #1829

Add encoding field to cs_x86 in python bindings for consistency

---

arch/AArch64/AArch64MappingInsnOp.inc
suite/regress/test_arm64_ldr_registers.py

Fix for ldapr, and unit test for ldapr + ldr instructions (issue #1839).
I don't know yet how to fix the ldr incorrect information, hopefully someone else knows?

Fix AArch64 ldapr detailed information #1839
