capstone-engine/capstone

bindings/python/pyx/ccapstone.pyx
Per issue #248, and #249, I have rebased my changes to the next branch. I did not touch the base memory leak (which had already been fixed) and only added the correction to the cython bindings.
=> - Fixed memory leak for cython disasm functions

msvc/capstone_static/capstone_static.vcxproj, msvc/test/test.vcxproj, msvc/test_arm/test_arm.vcxproj, msvc/test_arm64/test_arm64.vcxproj, msvc/test_detail/test_detail.vcxproj, msvc/test_mips/test_mips.vcxproj, msvc/test_ppc/test_ppc.vcxproj, msvc/test_skipdata/test_skipdata.vcxproj, msvc/test_sparc/test_sparc.vcxproj, msvc/test_systemz/test_systemz.vcxproj, msvc/test_x86/test_x86.vcxproj, msvc/test_xcore/test_xcore.vcxproj
The previous test binaries generated still had the MSVC++ CRT dynamically linked. This pull request fixes that by just enabling /MD(d) on the static library & every test projects.
=> /MT(d) -> /MD(d)

msvc/capstone_dll/capstone_dll.vcxproj
Linking MSVCRT statically to capstone_dll.
=> Using /MT(d) for capstone_dll

arch/ARM/ARMDisassembler.c, arch/ARM/ARMInstPrinter.c
Hi,
The `ldrh r0, [r1, #-2] (\xB2\x00\x51\xE1)` has incorrect mem.disp = -258 instead of -2.
=> Correct printAM3PreOrOffsetIndexOp disp value

Makefile, make.sh
- Remove bashisms (use posix shell)
- Use only two space indentation (no mixed tabs)
- Honor $0 and autogenerate help message
- Correct use of exported and local vars
- Simplify spaguetti (-30LOC)
- Update copyright year
- Quote all vars to avoid command injection
- Cache uname value and allow to override it
- Honor user environment
- Support MAKE_JOBS (by default is 4)
=> Rewrite make.sh to make it shorter, faster and more portable

arch/AArch64/AArch64InstPrinter.c, arch/ARM/ARMModule.c, arch/Mips/MipsModule.c, arch/X86/X86DisassemblerDecoder.c, arch/X86/X86Module.c, cs.c, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Dynamic Library.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Framework.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Static Library.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
This Xcode-centric PR tweaks Xcode project settings, silences several warnings about type conversions, and silences one warning about a possibly uninitialize variable.
=> Silencing Clang warnings

.gitignore, xcode/Capstone.xcodeproj/project.pbxproj
This updates the Xcode project to point the headers group to the right physical directory.
Apparently my `next` branch had a handful of commits from October that I never brought forward. Sorry for the history pollution. It's all been overwritten with the official `next` branch.
=> Xcode project merge

include/x86.h
Fixed type for cs_x86_op reg to be a x86_reg instead of unsigned int.  This makes it easier to understand that reg is a x86_reg enumeration versus something else.  It is currently not clear which type reg is.
=> Changed type for cs_x86_op.reg

bindings/python/setup.py
This allows you to
`python setup.py develop`
and work from your local copy. As far as I know it's a drop in replacement.
=> python: Use setuptools instead of distutils to setup

bindings/python/Makefile
Without this patch, DESTDIR is ignored, so build systems that use a
staging sandbox prior to installing in real-root, such as Gentoo,
cannot build the python binding.
Caveats:
1) I wrote/tested this against the 3.0.2 release, not current HEAD.
2) It might be preferable to do DESTDIR ?= / at the top of the Makefile,
so that the if/else/fi can be squashed back out.
3) The install_cython target probably needs a similar change; untested.
4) Other bindings might need something similar.
=> Add DESTDIR support for the python binding.

CMakeLists.txt, MCInst.c, Makefile, SStream.c, arch/X86/X86ATTInstPrinter.c, arch/X86/X86DisassemblerDecoder.c, arch/X86/X86DisassemblerDecoder.h, arch/X86/X86IntelInstPrinter.c, cs.c, include/capstone/capstone.h, myinttypes.h, osxkernel_inttypes.h, utils.c
Capstone 3.0.x branch doesn't work with OS X kernel extensions due to some include files that do not exist in OS X kernel framework headers.
This patch adds a new option that includes libkern/libkern.h, replacing the includes that do not exist.
It now works out of the box (I always copy and include full Capstone source code into my kexts). Might need some minor changes in the configuration scripts.
Pedro
=> Add support to embed Capstone 3.x branch into OS X kernel extensions.

CMakeLists.txt, arch/Mips/MipsDisassembler.c
Fix nmake build,
give msvc + cmake a different target for the .lib file,
otherwise the shared target .lib will be overwritten by the static target .lib
=> MSVC related fixes

arch/X86/X86IntelInstPrinter.c, arch/X86/X86Mapping.c, arch/X86/X86Mapping.h
Bug:
00491AD0  A0 11 12 13 14            mov al, byte ptr [0x14131211]
Prefix:0x00 0x00 0x00 0x00
Opcode:0xa0 0x00 0x00 0x00
addr_size: 4
op_count: 1
operands[0].type: MEM
operands[0].mem.disp: 0x14131211
operands[0].size: 1
=> [x86] Fix decode opcode A0 and A1 (movabs)

CMakeLists.txt
Headers and source are grouped per project.
Adapted from https://github.com/aquynh/capstone/pull/317 for the next branch
=> Split headers and source in CMake

arch/X86/X86DisassemblerDecoder.c
This was discovered when Frida's Stalker encountered the following
x86-64 instruction while tracing code in ntdll: `f0 49 0f c7 0a`.
=> Fix handling of cmpxchg16b with lock prefix

Makefile
The destination directory may not exist, so we need to mkdir just
in case.
=> Improve the pkgconfig target

suite/test_group_name.py
Also test out-of range values (by overshooting the current max for all arches).
This relies on a small hack (directly importing the ctypes from capstone), because the Cs object does not expose the cs_group_name function directly.
=> Validate group names against a hardcoded list per arch.

bindings/python/capstone/__init__.py, suite/test_group_name.py
And added missing group names to the test,
as well as slightly changed the functions in CsInsn (always returns a default on invalid instruction, instead of in some cases None, and in other cases "(invalid)"
=> reg_name, insn_name, group_name in Cs

include/capstone.h
I was playing with this awesome disassembly engine and while reading the awesome code documentation, I made a few minor spelling fixes along the way and since I follow the Boy Scout rule, wanted to contribute them back.
Thank you for this engine!
=> Fix spelling nits

bindings/python/capstone/__init__.py
During cleanup, it's possible that the _cs object is None on the line below, which throws the error.
```
Exception AttributeError: "'NoneType' object has no attribute 'cs_close'" in <bound method Cs.__del__ of <capstone.Cs object at 0x1d0cb10>> ignored
```
https://github.com/aquynh/capstone/blob/b238628e37b09c2fba09b0209ecafa2c73b35031/bindings/python/capstone/__init__.py#L694
```py
def __del__(self):
if self.csh:
status = _cs.cs_close(ctypes.byref(self.csh))
if status != CS_ERR_OK:
raise CsError(status)
```
=> Fix error when _cs is None during teardown

arch/PowerPC/PPCInstPrinter.c, bindings/java/capstone/Ppc.java, bindings/java/capstone/X86.java, include/capstone/ppc.h, tests/test_ppc.c
The imm variant of an instruction is defined as as int32_t. Indeed, an
immediate cannot be wider than that in a PowerPC instruction.
However, for branching instruction with AA=0, the field contains the
real target address (offset + CIA) instead of the offset: the real
target address might be outside of the 32 bit address space.
=> Make PowerPC imm 64 bit (instad 32 bit)

bindings/python/setup.py
These changes will allow a pypi user to locally install capstone using the --user flag. If it possible, please update the correspondent package (https://pypi.python.org/pypi/capstone/3.0.3)
=> Allow local installations of the python bindings

COMPILE.TXT, make.sh
These changes do two things. 1. Allows specifying additional arguments to make(1). For example, passing -j8 to utilize multiple cores when building. 2. Supports building using the Android NDK much better. The Android build process now only requires pointing to the NDK path using $NDK.
=> Improve make.sh: Better Android building and allow passing extra stuff to make(1)

.gitignore, bindings/python/setup.py
See aquynh/capstone#405. The commits merge cleanly but for some reason github is having issues with them...
=> [master] Virtualenv support for Python binding

.gitignore, bindings/python/setup.py
**In a [virtualenv] (http://pypi.python.org/pypi/virtualenv):**
* `site.getusersitepackages` won't import
* `distutils.sysconfig.get_python_lib` will return the directory inside the virtualenv
* the `--user` option can therefore be safely ignored.
I also added the generated capstone.egg-info directory to the .gitignore list.
=> [next] Virtualenv support for Python binding

CMakeLists.txt
This fixes building by CMake.
http://lists.derevenets.com/pipermail/capstone-buildbot/2015-June/000221.html
=> Remove reference to missing osxkernel_inttypes.h from CMakeLists.txt

make.sh
When the CC variable has a multi-string value like when using ccache(CC="ccache gcc"), it currently throws a warning. Fix such issues, also when passing CC to make.
=> Fix check for multi-string CC

packages/rpm/capstone.spec
Here's the new spec file for 3.0.4. Fixes a build issue due to missing/wrong %license macro for EPEL6, besides that the changes are obvious.
Fedora/EPEL builds using this spec file are now available via COPR:
https://copr.fedoraproject.org/coprs/scorneli/capstone/
=> Update to 3.0.4. Fix EPEL6 build issue

Makefile
Don't redefine ``$LIBDATADIR`` when global environment variable
``USE_GENERIC_LIBDATADIR`` is set. This is used by the pkgsrc framework.
=> Allow to build capstone in pkgsrc for FreeBSD and DragonflyBSD

CMakeLists.txt
cmake options can be used to disable certain architectures, which is very helpful for reducing the binary size. For instance cmake -DCAPSTONE_X86_SUPPORT=OFF can be used to exclude X86 related code from being compiled. At the same time tests like test.c, test_iter.c, etc reference all architectures, so they fail when one of the architectures is turned off. To avoid this, support options are propagated to the preprocessor, where they can be used to conditionally include architecture specific code.
Sorry about this. I did more testing this time and included diagnostic to make sure the issue is really resolved.
=> Fix bug in option propagation.

CMakeLists.txt
Enable MACOSX_RPATH in cmake versions >= 3.0 to resolve the cmake warning.
=> Fix policy warning

CMakeLists.txt
For now use old policy behavior to preserve backwards compatibility, but I strongly recommend updating the minimum cmake version, since it's considered a best practice.
http://www.slideshare.net/DanielPfeifer1/cmake-48475415 (slide 21)
=> Resolve cmake project version policy warning

bindings/const_generator.py
Avoid "TypeError: a bytes-like object is required, not 'str'" error during
write().
As the outfile need to be opened in binary mode, so python 3 require bytes
stream as argument in outfile.write().
Fixed by set all output string write to utf-8 encoding.
Signed-off-by: Nicolas PLANEL <nplanel@gmail.com>
=> file.write() need bytes when file is opened in binary mode

arch/M68K/M68Kdasm.c, bindings/python/capstone/__init__.py, contrib/objdump/objdump-m68k.py
[contrib][objdump] remove un needed import
[binding][python] fixup python 3 compatibility
[M68K] CPUSH CINV should return INVALID opcode is case of error.
=> M68k fixup

arch/M68K/M68KDisassembler.c
Remove spaces at the end of lines, remove unnecessary brackets and avoid declaring variables after the begining of the stackframe.
=> Indentation fixes

arch/M68K/M68KDisassembler.c, arch/M68K/M68KDisassembler.h, arch/M68K/M68KInstPrinter.c, arch/M68K/M68KInstPrinter.h
[M68K] remove global dependency aim to have reentrant code
[M68K] Use printer_info to share private info between disassembler and printer
=> Print info

arch/M68K/M68KDisassembler.c
if(info) should be removed as it's an old part of the code that has been forgotten before merging.
Didn't cause any Bug as info is always true.
Related to issue #494
Signed-off-by: Nicolas PLANEL <nplanel@gmail.com>
=> [M68K] Coverity fixup : remove old/dead code.

bindings/python/capstone/__init__.py
El Capitan does not guaranteed that
(DY)LD_LIBRARY_PATH will exist, so force
one last check for the default install
directory that the install script uses.
=> Add OSX 10.11 dylib load fix

bindings/java/capstone/Capstone.java
When Capstone considers the first instruction of the stream broken it returns with a null reference.
Dereferencing this reference - insnRef.getValue() -  throws a NullPointerException.
Instead the condition is checked and the routine returns properly a null result instead.
=> Fix NPE when first instruction to disassemble is broken.

bindings/python/capstone/__init__.py
Choose `CsError.__str__` implementation based on Python version.
Momentarily forgot Python's indentation rules.
=> Python 3: CsError.__str__

arch/X86/X86Disassembler.c
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
* [Linux kernel coding style](https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892)
* [Living in the #ifdef Hell](https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/)
It might improve code understanding, maintainability and error-proneness.
=> Refactoring conditional directives.

Makefile
added __APPLE_CC__ to IS_APPLE test
=> fix building on 10.6.8

include/ppc.h, tests/test_ppc.c
use the available ppc_reg typedef instead of the generic unsigned int
=> improve type safety, use ppc_reg instead of unsigned int

Makefile
simplified IS_APPLE grep command by having it return count, with a max find limit of 1 for both Apple $(CC) expected patterns
=> fix building on 10.6.8 without breaking other versions

Makefile
this change is apparently already on master
it is needed for ./make.sh cross* to work
=> fix setting cross compilation variables

arch/ARM/ARMMapping.c
All jump instructions have been classified based on the direct
and indirect_branch flags instead of explicitly stating ARM_GRP_JUMP.
I'm reopening this PR since I messed up with git history in the last time. Sorry for that.
=> Fix classification of ARM jump instructions

arch/ARM/ARMInstPrinter.c
This is for the bug reported in issue #580, see the attachment there for a test case. The problem does occur in the "next" branch.
=> Align thumb BLX immediate by discarding low bits (for issue #580)

bindings/python/MANIFEST.in, bindings/python/setup.py
This fixes  #588 and possibly also #583. It seems that more recent setuptools do not like to place files outside the installed package with the data_files directive. So it is better to use the package_data directive to ensure the shared objects end up inside the package. 
This change also allows creating a wheel:
```
$ python setup.py bdist_wheel
....
Copying capstone.egg-info to build/bdist.linux-x86_64/wheel/capstone-3.0.4.data/purelib/capstone-3.0.4-py2.7.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/capstone-3.0.4.dist-info/WHEEL
$ ls dist/
capstone-3.0.4-cp27-none-linux_x86_64.whl  capstone-3.0.4-py2.7.egg  capstone-3.0.4.tar.gz
$ unzip -l dist/capstone-3.0.4-cp27-none-linux_x86_64.whl
Archive:  dist/capstone-3.0.4-cp27-none-linux_x86_64.whl
Length …
```
=> Fix setup.py to use setuptools and put the libcapstone.so in the right place.

Makefile
test and test.basic are now test_basic and test_basic.static. Rename them in the
Makefile as such to avoid 'make check' error.
=> Update available tests

arch/X86/X86ATTInstPrinter.c, arch/X86/X86IntelInstPrinter.c, arch/X86/X86Mapping.c, arch/X86/X86Mapping.h
This PR fixes a regression introduced by #316, and set the access fields of some « MOV » instructions to the correct value.
=> Fixes access field information for some MOV instructions

arch/X86/X86MappingInsnOp.inc, arch/X86/X86MappingInsnOp_reduce.inc
Fixed the destination access flags for MOVABS instruction, it should be CS_AC_WRITE instead of CS_AC_IGNORE.
=> Fixed MOVABS flags

arch/PowerPC/PPCInstPrinter.c
Fixes the following bug:
On 64-bit PPC a branch, like “bce TARGET” gets the target truncated to 32-bits.
```
00003fff76030028 bge    0x760300c0 # this is really branching to the ld instruction, below.
...
00003fff760300c0 ld     r6, -8(r20)
```
=> Do not truncate branch target address to 32 bit

arch/M68K/M68KDisassembler.c
See m68k Programmer's Reference Manual pp. 4-128
The operands are always stored in the order re,ea, the direction bit only changes the assembler syntax.
The mask bits are only reversed for the predecrement mode addresses (only valid for register-to-memory transfers). Maybe one of the coders for this arch should have a look at it as I am sort of new to this subject. However, I can confirm that two different assemblers reproduce the original binary code (vasm and asmx).
=> bugfix: use proper order for operands in M68K movem

include/capstone/arm.h, include/capstone/arm64.h, include/capstone/mips.h, include/capstone/ppc.h, include/capstone/sparc.h, include/capstone/systemz.h, include/capstone/xcore.h
In some architecture headers, register values were
represented as `unsigned int`/`uint8_t` or other types
instead of the corresponding enums. This commit fixes most (all)
occurences of this problem.
Fixes the second part of issue #619.
=> Fixed register types

arch/AArch64/AArch64BaseInfo.c, cs.c, include/arm.h, include/arm64.h, include/capstone.h, include/mips.h, include/platform.h, include/ppc.h, include/sparc.h, include/systemz.h, include/x86.h, include/xcore.h, msvc/capstone_static/capstone_static.vcxproj, myinttypes.h, tests/test.c, tests/test_arm.c, tests/test_arm64.c, tests/test_detail.c, tests/test_iter.c, tests/test_mips.c, tests/test_ppc.c, tests/test_skipdata.c, tests/test_sparc.c, tests/test_systemz.c, tests/test_x86.c, tests/test_xcore.c
Those changes are to compile Capstone and run existing all regression tests for Windows drivers in Visual Studio 2015. Details of changes are explained in this page.
https://github.com/tandasat/cs_driver
Note that changes in capstone_static.vcxproj will be a breaking change since it was converted into a new version of a project file.
It is my first time to create a pull request, so let me know anything I can do for smooth code merge
=> Support compile Capstone and run tests for drivers in Visual Studio

.gitignore
This changes is to ignore a couple of VS2015 cache files and output directories created when capstone_static project is compiled for a driver.
=> ignore VS2015 cache files and Debug|Release_WDK folders

include/arm.h, include/arm64.h, include/capstone.h, include/mips.h, include/ppc.h, include/sparc.h, include/systemz.h, include/x86.h, include/xcore.h
To fix an issue (I made), revert API headers to use stdint.h.
https://github.com/aquynh/capstone/commit/760940fdceb50a09f1a8ebee5dc807b6039f144e
This change breaks support of drivers obviously, but its impact will be nearly zero at this time. Sorry for this errors, I will work on a right fix after we have discussed a solution.
=> replace stdint.h in API headers 

arch/M68K/M68KDisassembler.c
* instruction is available for all processors, not 68010+ (see e.g.
https://www.nxp.com/files/archives/doc/ref_manual/M68000PRM.pdf, p. 6-19)
* operand size is WORD not BYTE
=> m68k: fixed d68000_move_to_sr

bindings/python/capstone/__init__.py
=> __getattr__ should raise AttributeError, not return None, on failure

bindings/python/Makefile
Currently, if python tests fails, we still report that build succeeded. For example, see: https://travis-ci.org/aquynh/capstone/jobs/126903560#L328
This failure should not be reported  as success. Fix this by returning non-zero value from Makefile. It will now fail as expected. For example, see: https://travis-ci.org/pranith/capstone/jobs/126907904#L413
=> Properly exit on python test failure

.travis.yml, Makefile
The build script currently generates library as libcapstone.so. But the name given to the library is libcapstone.so.4. I think it is better to generate a library with the same file name as the given library name to avoid any confusion.
This also helps when you do not install the library system-wide but set LD_LIBRARY_PATH to the capstone directory. In such cases, we look for libcapstone.so.<version> and will not find it.
=> Fix generated library name

arch/Mips/MipsMapping.c, arch/Mips/MipsMappingInsn.inc, bindings/java/capstone/Mips_const.java, bindings/ocaml/mips_const.ml, bindings/python/capstone/mips_const.py, include/capstone/mips.h, suite/test_group_name.py
Also annotates the `jalr` and `syscall` instructions to have these groups.
Since I was adding these two generic groups, I added all of the generic groups.
=> Add MIPS_GRP_INT and MIPS_GRP_CALL

bindings/python/test_m68k.py, tests/test_m68k.c
* added a new case branch to account for floating point operands.
As mentioned in #677, the `m68k` tests broke (although it isn't clear what exactly caused that).
This pull request fixes this in a trivial manner, which appears right to me.
=> Reduced confusion caused by the m68k test being out of date

bindings/python/test_arm.py, bindings/python/test_basic.py, bindings/python/test_detail.py, bindings/python/test_lite.py, bindings/python/test_skipdata.py, bindings/python/test_x86.py
Comparing against 0 or just testing the truthiness is suboptimal, as you
lose the ability to explicitly set the syntax to `CS_OPT_SYNTAX_DEFAULT`
or 0.
Also, using `None` to mean "don't change" or other "here is no value"
interpretations is much more pythonic than the C-idiomatic 0.
=> [Python] Use and test syntax against None in all_tests.

bindings/python/capstone/__init__.py, bindings/python/capstone/arm.py, bindings/python/capstone/arm64.py, bindings/python/capstone/mips.py, bindings/python/capstone/ppc.py, bindings/python/capstone/sparc.py, bindings/python/capstone/systemz.py, bindings/python/capstone/x86.py, bindings/python/capstone/xcore.py
Previously, capstone didn't work in pypy. The basic example script failed.
The struct-copy trick that was copied from that one stack overflow post doesn't work in pypy's implementation of ctypes, so I replaced it with one of the other answers from that post.
Additionally, the use of deepcopy was erroring out on pypy, so I replaced it with a more direct method. This involved rearranging some imports so the submodules could import a method from the main `__init__.py`.
A more long-term solution would be to switch from ctypes to cffi.
=> change structure copying so python bindings work in pypy

arch/X86/X86MappingInsnOp.inc, arch/X86/X86MappingInsnOp_reduce.inc
I think X86_INS_POP currently has wrong access flags. I tested Capstone Next with the following input:
pop dword ptr ds:[0]
pop dword ptr ss:[esp]
And received the following output:
"pop dword ptr ds:[0]": operands[0].type =MEM, operands[0].access = READ.
"pop dword ptr ss:[esp]": operands[0].type =MEM, operands[0].access = READ.
So the output is wrong because the memory locations "dword ptr ds:[0]" and "dword ptr ss:[esp]" are accessed in WRITE mode (the POP instruction extract the value on the top of the stack and saves it in the destination reg/mem).
In the pull request I changed the access flags for the instruction "POP [MEM]" to CS_AC_WRITE, now the output is right.
=> Changed X86_INS_POP flags

bindings/python/capstone/m68k.py
This replacement was done for commit
16477206564745782854e0ec5c68defa02429dd8, allowing the python binding to
be used in PyPy. It seems the m68k arch has been forgotten.
=> Replace copy.deepcopy by  copy_ctypes_list for get_arch_info

arch/X86/X86MappingInsnOp.inc, arch/X86/X86MappingInsnOp_reduce.inc
MOV addr to register access weren't quite correct :  the dst register is always written in those cases.
=> [X86] Fix *ax dst register access on some MOV instructions

arch/X86/X86DisassemblerDecoder.c
Per discussion on #656. Please check carefully - I'm not by any means an expert on x86 instruction encoding, or capstone.
=> x86: initialize eaDisplacement in 16-bit mode.  Fixes #656

arch/M68K/M68KDisassembler.c, arch/M68K/M68KDisassembler.h, arch/M68K/M68KInstPrinter.c, bindings/python/test_m68k.py, tests/test_m68k.c
Implemented so the ``regs_read`` and ``regs_write`` arrays gets filled with the correct data for the M68K backend.
Also added some more data in the ``m68k.c`` to show this of and also printing of the read/written registers. These changes were mirrored in the ``test_m68k.py`` python version also.
cc @nplanel for visibility and review
=> [M68K] Implemented regs read/write lists

arch/AArch64/AArch64InstPrinter.c
Even if "sxtb" was printed, the ext field was not set with the right value
=> AArch64 set good extender

arch/X86/X86DisassemblerDecoder.c
Caught by Valgrind:
Conditional jump or move depends on uninitialised value(s)
at 0xD5BB6F: readModRM (X86DisassemblerDecoder.c:1528)
by 0xD5BF02: getIDWithAttrMask (X86DisassemblerDecoder.c:1101)
by 0xD5CC5E: getID (X86DisassemblerDecoder.c:1249)
by 0xD5CC5E: decodeInstruction (X86DisassemblerDecoder.c:2335)
by 0xD52009: X86_getInstruction (X86Disassembler.c:822)
by 0xD51781: cs_disasm (cs.c:503)
=> Fix use of uninitialized value for some instructions

.gitignore, COMPILE_MSVC.TXT, HACK.TXT, arch/AArch64/AArch64BaseInfo.c, arch/Sparc/SparcInstPrinter.c, arch/XCore/XCoreInstPrinter.c, contrib/cs_driver/cs_driver/cs_driver.c, cs.c, docs/README, include/x86.h, tests/test_winkernel.cpp, windows/winkernel_mm.c, windows/winkernel_mm.h
This PR:
- fixes some typo and style issues
- suppresses some warnings reported by PREfast (Static Code Analysis) that are FP (eg, 30030) or already ignored in case they are reported as non-PREfast warnings (eg, 28719 vs 4996)
- ignores files that are created when VS converts existing project files to the latest version of them
=> Fix typo, style, suppress MSVC PREfast warnings, ignore residual files on project upgrade 

bindings/python/setup.py
When the python bindings are installed using the new wheels
infrastructure, data_files are relative to the site-packages directory
even if using absolute paths.
The following example demonstrates the bug fixed by this commit: (ran on archlinux)
```bash
$ pip install wheel       # if this package is installed, wheel installation is made the default
Collecting wheel
Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
100% |################################| 71kB 124kB/s
Installing collected packages: wheel
Successfully installed wheel-0.29.0
$ pip install capstone    # this will use the wheel installation method now
Collecting capstone
Using cached capstone-3.0.4.tar.gz
Building wheels for collected packages: capstone
Running setup.py bdist_wheel for capstone ... done
Stored in directory: …
```
=> python-bindings: fix setup.py for wheel installation

bindings/python/capstone/__init__.py
There's probably some more elegant fix for this, but currently everything breaks if you hand memory from unicorn directly into capstone.
There's also not any obvious tests, so I didn't add a regression test, but let me know if I should have somewhere.
=> Workaround unicorn handing back bytearrays

bindings/python/capstone/__init__.py
The `pointer(...)[0] = ...` idiom doesn't play nicely with pypy's implementation of ctypes. This patch should also be ported to the master branch.
Patch credit @ltfish
=> Change pointer-deref-then-assignment to memmove to make PyPy happy.

arch/X86/X86MappingInsn.inc
```
from capstone import *
from capstone.x86 import *
md = Cs(CS_ARCH_X86, CS_MODE_64)
md.detail = True
insn = next(md.disasm("\xF9", 0x00))
print "0x%016X    %s %s" % (insn.address, insn.mnemonic, insn.op_str)
print "reg_read     => ", insn.regs_read
print "reg_write    => ", insn.regs_write
print X86_REG_EFLAGS in insn.regs_write
```
Result:
```
0x0000000000000000    stc
reg_read     =>  []
reg_write    =>  []
False
```
The STC instruction doesn't show that EFLAGS will been written.
Expected result:
```
0x0000000000000000    stc
reg_read     =>  []
reg_write    =>  [25]
True
```
=> add X86_REG_EFLAGS for X86_STC

arch/ARM/ARMDisassembler.c
=> Use the correct mapping for 32-bit Thumb Big-Endian insns

ChangeLog, bindings/java/capstone/Arm.java
Fix an incorrect type in the Java binding which causes incorrect field values.
=> Java: Fix a bug where Arm.Operand is wrongly calculated for the second and following operands

ChangeLog, bindings/java/capstone/Arm.java
Fix an incorrect type in the Java binding which causes incorrect field values.
=> Java: Fix a bug where Arm.OpInfo.memBarrier and Arm.OpInfo.op is wrongly calculated

ChangeLog, bindings/java/capstone/Capstone.java
Add two more functions to the Java binding: cs_strerror() as Capstone.strerror() and cs_regs_access() as CsInsn.regsAccess().
=> Java: Support cs_strerror() and cs_regs_access()

Makefile
Without this, installing to a temporary directory tree (as done by
some package managers) installs cstool as the file /usr/bin.
This brings next in line with the behavior of master.
=> Make sure bindir exists before installing to it.

cstool/cstool.c, include/platform.h
cstool.c currently imports `inttypes.h`, which breaks building on older Visual Studio versions (I've been testing 2012). This commit removes the explicit include of `inttypes.h`, which is already handled in `platform.h` (which is included by `capstone.h`). A define for the function `strtoull` (used by `cstool`) has also been added to `platform.h` for the case where `MSC_VER <= 1700`.
I don't know what effect this will have on OS X builds as I'm unable to test on that platform. I've tested it successfully on Ubuntu (i.e. I've run make.sh with no complaints.)
Also, `cstool.c` doesn't need to include `stdio.h` because it's already included by `capstone.h`.
=> Fix build under VS2012 (i.e. MSC_VER = 1700)

arch/ARM/ARMMapping.c
The SETEND instruction is a 16 bit Thumb instruction which is included
in T variants of ARMv6 and above, but is not available in M-Class cores
(see ARM Compiler toolchain Assembler Reference Ver 5.0).
To be consistent with other similar instructions its group flags have
been updated to be:
{ARM_GRP_THUMB, ARM_GRP_V6, ARM_GRP_NOTMCLASS,0}
=> Patch for issue #842

arch/M68K/M68KDisassembler.c
8-bit displacement was treated as unsigned while it should actually be signed.
Ref https://github.com/aquynh/capstone/issues/844
=> [M68K] Fixed incorrect 8-bit displacement

arch/AArch64/AArch64InstPrinter.c
The instruction encoded « 00 00 19 B2 » was correctly disassembled « orr x0, x0, #0x8000000080 », but the reported immediate value, in the detail structure, was truncated to 0x80 due to the cast.
=> Fixes truncated immediate value in operand details

utils.h
Now that capstone is getting close to the release of a new version, would you be so kind to fix the compilation error arising when you try to compile it into the macOS kernel? There is no stddef.h file in Kernel.framework and thus an include is invalid.
Also, might you want to delete [this line](https://github.com/aquynh/capstone/blob/f177f92a7c9bea2dd7259577175cfa13579ec425/cs.c#L326)? I remember receiving a compiler warning for it.
=> Fix compilation from within a macOS kernel extension

arch/X86/X86ATTInstPrinter.c
Bug found in r2 and patch tested for a week or so
Ref: https://github.com/radare/radare2/blob/master/shlr/capstone-patches/fix-undef.patch
=> Fix UB when accessing un-initialized array

arch/X86/X86Disassembler.c
Bug found by @h4ng3r and fixed by @trufae in radare2 https://github.com/radare/radare2/commit/d692bfb37a28965b7824b8486baeaeaab630dbb8
cstool reproducer and proof:
=> Fix undefined behaviour produced by disassembling 6662dcbc615a

arch/X86/X86Disassembler.c, utils.c
The insn_cache array was not set for index 0.
But it happens that insn_find can look for id 0.
And so, insn_find may return something bigger than max and we get a set fault.
This happened on a compilation on Linux with gcc -O3
=> Bugfix : setting all fields to insns cache

CMakeLists.txt
It was set as a global property before, but cmake appears to ignore that,
even after the following fix:
-set_property(GLOBAL PROPERTY SOVERSION SOVERSION ${VERSION_MAJOR})
+set_property(GLOBAL PROPERTY SOVERSION ${VERSION_MAJOR})
So this patch removes the global property, and SOVERSION is now specified as
a target specific property. The result of the cmake install target seems better:
Before:
```
$ ls -la lib
4375834 May  1 16:05 libcapstone.a
3510040 May  1 16:05 libcapstone.so
```
After:
```
$ ls -la lib
4375834 May  1 16:05 libcapstone.a
16 May  1 16:08 libcapstone.so -> libcapstone.so.4
20 May  1 16:08 libcapstone.so.4 -> libcapstone.so.4.0.0
3510040 May  1 16:08 libcapstone.so.4.0.0
```
The SOVERSION property triggers symlink creation in cmake, see: …
=> cmake - fix SOVERSION property used for libcapstone.so

arch/X86/X86GenAsmWriter1.inc, arch/X86/X86GenAsmWriter1_reduce.inc, arch/X86/X86IntelInstPrinter.c, arch/X86/X86Mapping.c, cs.c, include/capstone/capstone.h, include/capstone/platform.h
This implements the changes made in #929 along with two small header fixes to get things compile for OS X kernel.
While these two changes are exactly necessary, there are (at least) two more changes for next branch to be used in the kernel:
1. qsort — there is no public KPI for it
2. Vulnerability fix https://github.com/aquynh/capstone/pull/725#issuecomment-301737249, this remains present in next branch.
Could you fix both of these on your own? They clearly are not part of this PR.
There are multiple qsort implementations with permissive licenses: [example 1](https://opensource.apple.com/source/xnu/xnu-3248.60.10/bsd/kern/qsort.c.html), [example 2](https://opensource.apple.com/source/Libc/Libc-1158.50.2/stdlib/FreeBSD/qsort.c.auto.html), [example …
=> Merge #929 with some changes to get things compile

Makefile, cstool/Makefile
The correct compiler was not being passed to `cstool/Makefile`. The expected name for the capstone lib was also incorrect - there is no "lib" prefix when compiling with mingw.
=> mingw build: cstool fails to build with mingw

arch/Mips/MipsDisassembler.c, arch/Mips/MipsModule.c, bindings/java/capstone/Capstone.java, bindings/ocaml/capstone.ml, bindings/ocaml/ocaml.c, bindings/python/capstone/__init__.py, include/capstone/capstone.h, tests/test_mips.c
If both CS_MODE_MIPS2 and CS_MODE_MIPS3 are set, MIPS3 wins.
It's possible to set CS_MODE_MIPS2 also in combination with CS_MODE_{MIPS32|MIPS64} because the first versions of those specs were based on Mips II. In this case the opcodes for the new doubleword instructions won't be available since they overlap with COP3 (coprocessor 3) instructions.
Intended to fix https://github.com/aquynh/capstone/issues/938
=> Add CS_MODE_MIPS2 to opt-in for COP3 instructions

cstool/Makefile
Previously, the CFLAGS= statement would strip --sysroot from CFLAGS.
=> Fix the include path for Android builds when building cstool

cstool/cstool.c
=> cstool: Separate instruction bytes by spaces

capstone.pc.in
cmake pkg-config file fixed hardcoded paths with variables. CMakeLists.txt line 394 needs to be modified
> configure_file("capstone.pc.in" "capstone.pc" @ONLY)
=> fixed hardcoded paths with variables.

arch/Mips/MipsModule.c
handle->disasm was incorrectly set to `Mips64_getInstruction` if `CS_MODE_MIPS32R6`
was set but `CS_MODE_32` was not set.
If you change the mode at runtime with `cs_option` (instead of the initial `cs_open`), then the wrong disassembler handle is picked. You can observe the bug by applying the following patch to `test_mips.c`:
~~~diff
--- ../tests/test_mips.c        2017-10-04 01:02:46.392004908 -0700
+++ ../tests/test_mips_set_option.c     2017-10-04 01:17:35.682116291 -0700
@@ -120,12 +120,13 @@
size_t count;
for (i = 0; i < sizeof(platforms)/sizeof(platforms[0]); i++) {
-               cs_err err = cs_open(platforms[i].arch, platforms[i].mode, &handle);
+               cs_err err = cs_open(platforms[i].arch, 0, &handle);
if (err) {
printf("Failed on cs_open() with error returned: …
=> Fix selection of mips disasm handler

.travis.yml
https://bintray.com/homebrew/bottles/capstone#statistics
look at the 1 year view to get the last update on may 4, showing 14k installs
current issue is a `travis` issue, wait for `travis` to fix
=> start watching brew HEAD builds

MCInst.c, utils.c
The MCInst structure was not being initialized properly, leading to undefined behavior, e.g. access violations when disassembling ud0 x86 instructions.
The change in utils.c isn't strictly necessary, but might prevent similar bugs in the future.
Maybe the special ud0 handling in X86Disassembler (marked FIXME) should also be adjusted, i.e. explicitly set instr->Opcode = 0 there.
=> Fix undefined behavior when disassembling ud0 x86 instructions

arch/M68K/M68KInstPrinter.c, bindings/python/capstone/m68k.py, include/capstone/m68k.h
This is one of those “how did this ever work?” changes. Problem was that as m68k_op was aliased with the imm value so when changing that to something big it would trash the values in the mem struct which would make things go really bad.
Now m68k_op_mem has been moved out of the union so this will not happen again. Also fixed instruction printing bug related to this (just happened to “work” due to the old union layout)
Fixes the problem outlined in #1025
=> [M68K] Fixed invalid base reg

.travis.yml, arch/AArch64/AArch64Disassembler.c, arch/AArch64/AArch64Module.c, arch/ARM/ARMDisassembler.c, arch/ARM/ARMModule.c, arch/Mips/MipsDisassembler.c, arch/Mips/MipsModule.c, arch/PowerPC/PPCDisassembler.c, arch/PowerPC/PPCModule.c, arch/Sparc/SparcModule.c, arch/SystemZ/SystemZModule.c, arch/X86/X86Module.c, arch/XCore/XCoreModule.c, cs.c, cs_priv.h
Using `cs_option()` to set the endianness fails for PowerPC.
The following code (based on `test_ppc.c`) will fail to disassemble without this fix:
~~~c
/* Capstone Disassembler Engine */
/* By Nguyen Anh Quynh <aquynh@gmail.com>, 2013> */
#include <stdio.h>
#include <platform.h>
#include <capstone.h>
struct platform {
cs_arch arch;
cs_mode mode;
unsigned char *code;
size_t size;
char *comment;
};
static csh handle;
static void print_string_hex(char *comment, unsigned char *str, size_t len)
{
unsigned char *c;
printf("%s", comment);
for (c = str; c < str + len; c++) {
printf("0x%02x ", *c & 0xff);
}
printf("\n");
}
static void test()
{
#define PPC_CODE "\x43\x20\x0c\x07\x41\x56\xff\x17\x80\x20\x00\x00\x80\x3f\x00\x00\x10\x43\x23\x0e\xd0\x44\x00\x80\x4c\x43\x22\x02\x2d\x03\x00\x80\x7c\x43\x2 …
=> ppc: fix endian check

bindings/README
`capstone-rs`, Rust bindings of capstone, have changed their project owner on github.
=> Update capstone-rs link

arch/Mips/MipsModule.c
Currently using Xcode 9.1 to build the provided Xcode project.  
Build issues the following warning:
capstone/arch/Mips/MipsModule.c:48:24: warning: implicit conversion loses integer precision: 'size_t' (aka 'unsigned long') to 'cs_mode' (aka 'enum cs_mode') [-Wshorten-64-to-32]
value = updated_mode(value);
Issue is in the `option` function in `MipsModule.c`:
static cs_err option(cs_struct *handle, cs_opt_type type, size_t value)
{
if (type == CS_OPT_MODE) {
value = updated_mode(value);
The `updated_mode` function takes an enum type (`cs_mode`) as parameter.  
On systems where `size_t` is 64-bits, this might trigger a warning, as it will implicitly convert a 64-bits value to a 32-bits value (enum is most likely an `int`).
An explicit cast will silence the error, and based on the …
=> Added an explicit cast to silence `-Wshorten-64-to-32` warning with clang.

xcode/Capstone.xcodeproj/project.pbxproj, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Dynamic Library.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Framework.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Static Library.xcscheme, xcode/Capstone.xcodeproj/xcshareddata/xcschemes/Tests.xcscheme
Previous update was for Xcode 6.3 (2015).
- Enabled recommended warnings
- Turned on «build active architecture only» in DEBUG mode
No issue when building with these updated setting.
=> Updated Xcode project for Xcode 9.1

xcode/Capstone.xcodeproj/project.pbxproj, xcode/CapstoneFramework/module.modulemap
The macOS framework target was lacking a [module map file](https://clang.llvm.org/docs/Modules.html#module-map-file).
Generating a proper module allows the Capstone API to be exposed to Objective-C using the `@import` syntax.  
**It also allows using Capstone with Swift.**
The module exposes all symbols from `capstone.h`.
I'll create a separate pull request for the `next` branch if this one is merged. : )
=> macOS framework - Added a module map for Swift/Objective-C.

arch/X86/X86MappingInsnOp.inc, arch/X86/X86MappingInsnOp_reduce.inc
the (E)DI register is incremented or decremented according to the setting of the DF flag in the EFLAGS register. If the DF flag is 0, the register is incremented; if the DF flag is 1, the register is decremented .
- intel manual
=> Fix EFLAGS for the stosb/stosd/stosq/stosw instructions

bindings/python/capstone/m68k.py
I noticed that the element order was incorrect for M68KOp when I tried using it from a Python program. With this change I can successfully inspect parts of disassembled 68k operands.
=> Reorder M68KOp elements to match order on C side

.gitattributes
Otherwise, they are considered to be PHP or C++ files, which causes GitHub's language statistics to show that Capstone is written mostly in PHP (42.2%) and C++ (33.1%), which is nonsense.
**Before:**
**After:**
Fore more information on how language statistics are computed, see [GitHub's linguist](https://github.com/github/linguist).
=> Fix language statistics by considering *.inc files to be C files

bindings/python/setup.py
Check to make sure static library file exists before trying to copy it. Current build options include option to not build a static lib.
=> Fix error in setup.py when not building static library

arch/X86/X86ATTInstPrinter.c, arch/X86/X86Disassembler.c, arch/X86/X86IntelInstPrinter.c, msvc/cstool/cstool.vcxproj
I disabled a few warnings from new calls to `strncpy`.
There were also couple missing references in the vcxproj for cstool.
=> Fix MSVC build in next branch

CMakeLists.txt
Currently, when you compile capstone on Linux using cmake, the generated capstone.pc file is broken:
```
prefix=/root/capstone-git/prefix
exec_prefix=
libdir=/lib
includedir=/include
Name: capstone
Description: Capstone disassembly engine
Version: 3.0.5
URL: http://www.capstone-engine.org
archive=/libcapstone.a
Libs: -L -lcapstone
Cflags: -I
```
You need to pass `@ONLY` to cmake's `configure_file()` to tell cmake to preserve pkg-config's `${}` expressions. This fixes the generated capstone.pc file:
```
prefix=/root/capstone-git/prefix
exec_prefix=${prefix}
libdir=${prefix}/lib
includedir=${prefix}/include
Name: capstone
Description: Capstone disassembly engine
Version: 3.0.5
URL: http://www.capstone-engine.org
archive=${libdir}/libcapstone.a
Libs: -L${libdir} -lcapstone
Cflags: …
```
=> Fix pkg-config output when using cmake

arch/X86/X86Disassembler.c
Prevent buffer overflow in cs_regs_access on ud0
By setting instr->Opcode, ud0 is correctly found in insns, and insn->detail is correctly initialized by X86_get_insn_id.
=> minimal patch to correct #1114 

arch/M68K/M68KDisassembler.c
Also added a sanity check that the code is at least 2 bytes before trying to disassemble.
Also removed some unused code while at it.
This should fix #1128 (also verified in r2 that this fixes the ASAN OOB read)
@nplanel I wonder if you remember this code here as you wrote it like 3 years ago :) To me the old bounds check seems wrong but maybe I missed something?
=> [M68K] Fixed incorrect size of code check

.travis.yml, Makefile
avoiding bash subshells (which happen in for loops) because they
like to selectively inherit environment variables
https://github.com/aquynh/capstone/pull/1023#issuecomment-389701608
=> Cleanup build process

arch/Mips/MipsDisassembler.c
Found using oss-fuzz (see #1145)
Shifting signed values is undefined behavior.
But we can multiply by 2.
=> Do not shift signed values in Mips disassembling

arch/M68K/M68KDisassembler.c
Found using oss-fuzz
Fixes an overflow in M68K disassembling, see also #1145
@emoon this is a clean pull request for the commit we discussed
=> Fix buffer overflow in M68K

arch/M68K/M68KDisassembler.c
Found using oss-fuzz (see #1145)
It looks to me that
```
info->regs_write[info->regs_write_count++] = (uint16_t)reg;
```
will first do `info->regs_write_count++` then `info->regs_write[info->regs_write_count] = (uint16_t)reg;`
and we want the other way around
=> M68K increment index after having written register

arch/X86/X86Disassembler.c
Adding initialization for `insn->detail->regs_read_count` and `insn->detail->regs_read_count` only is not faster than a full memset and might leave other bugs (what about `insn->detail->groups_count`?).
There are three initialization alternatives described in the commit, feel free to choose the one you prefer (you have write access to my branch).
Not initializing x86.operands should be safe and is 3% faster in my (limited) benchmarks with [test_iter_benchmark.c](https://github.com/aquynh/capstone/blob/863ec0aba8fbfdc83090ba21d3afad9e1a51d96c/suite/benchmark/test_iter_benchmark.c).
I did not chose this option as x86.operands was initialized in the original code base.
Reordering the fields makes it up to 8% faster (#1115) but breaks the bindings.
I could make it work for the ones included …
=> Improve init of cs_detail for x86 (#1114)

suite/fuzz/fuzz_disasm.c
Following commit 5315c5b7859b57c718c3b9e6b67e1dcbc6204cb9
see #1150
=> Fuzz next branch

arch/M68K/M68KDisassembler.h
Found using oss-fuzz see #1145 
Example is
```
0x1000:	movem.w		d0-d5/a0-a5, (a6) // insn-ID: 284, insn-mnem: movem
Implicit registers read: d0 d1 d2 d3 d4 d5 a0 a1 a2 a3 a4 a5 0x1004:
```
from instruction `48 96 3f 3f`
There are 2 more registers from the extension
=> We can read more registers from M68K

arch/AArch64/AArch64AddressingModes.h, arch/AArch64/AArch64Disassembler.c, arch/ARM/ARMAddressingModes.h, arch/ARM/ARMDisassembler.c, arch/Mips/MipsDisassembler.c, arch/PowerPC/PPCDisassembler.c, arch/Sparc/SparcDisassembler.c, arch/XCore/XCoreDisassembler.c
uint8_t gets promoted to integer
and integers shift cannot overflow on sign bit
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8673
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8674
=> Fix undefined shifts

SStream.c
Found using oss-fuzz
You cannot compute `- INT_MIN` as it is equal to `INT_MAX+1`
=> Print right hex value for MIN_INT

MCInst.c
Found using oss-fuzz (see #1145)
I am unsure if this is the right level for the fix.
Another fix could be to memset to zero the `Operands`array in function `MCInst_Init` in MCInst.c
=> use of uninitialzed value for operands type fix

arch/AArch64/AArch64InstPrinter.c
Use multiply instead
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8718
=> Fix undefined negative value shift

arch/SystemZ/SystemZInstPrinter.c
using fixed function from SStream.c in #1160 
If this change is correct, it could be done in lots of places (grepping for `HEX_THRESHOLD`)
=> Fix integer overflow on systemz

arch/ARM/ARMInstPrinter.c
Shift is for same operand as index register
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=8727
With instruction`12 f8 20 f0`
```
pld		[r2, r0, lsl #2] // insn-ID: 95, insn-mnem: pld
This instruction belongs to groups: thumb2 0x1004:
```
=> Fixes shift for ARM memory operand

arch/AArch64/AArch64InstPrinter.c, arch/ARM/ARMInstPrinter.c, arch/Mips/MipsInstPrinter.c, arch/PowerPC/PPCInstPrinter.c, arch/Sparc/SparcInstPrinter.c, arch/SystemZ/SystemZInstPrinter.c, arch/X86/X86ATTInstPrinter.c, arch/X86/X86IntelInstPrinter.c, arch/XCore/XCoreInstPrinter.c
in perticular, not to overflow -INT_MIN
Following #1164 
I do not think this is complete (there are still uses of HEX_THRESHOLD in arch directory), but it is already a big commit and deserves a review.
=> Use printint functions from SStream

suite/fuzz/fuzz_disasm.c, suite/test_corpus.py
Modifies the list of architectures and modes fuzzed
See https://github.com/google/oss-fuzz/pull/1508
@aquynh what do you think of this ?
I use `test_mc.py` to generate a corpus for fuzzing.
PS : It looks like `CS_MODE_MIPS32R6` is not tested...
Are all possible architectures and modes good after this ?
=> Builds a test corpus for fuzzing

arch/X86/X86DisassemblerDecoder.c
Sync with [upstream](https://github.com/llvm-mirror/llvm/blob/7cdce81/lib/Target/X86/Disassembler/X86DisassemblerDecoder.cpp#L362). The first check is done above, and the or operator was mistakenly replaced by a bitwise or operator. Was causing a warning for me.
=> Refactor confusing if for xacquire/xrelease

MCInst.c, SStream.c, arch/X86/X86ATTInstPrinter.c, arch/X86/X86Disassembler.c, arch/X86/X86IntelInstPrinter.c, arch/X86/X86Mapping.c, cs.c, utils.c
I thought my former 2 pull requests were all of it, but unfortunately not.
string.h in macOS SDK 10.13 looks like the following:
```C
extern void	*memcpy(void *, const void *, size_t);
…
#if defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED < __MAC_10_13
/* older deployment target */
#elif defined(KASAN) || (defined (_FORTIFY_SOURCE) && _FORTIFY_SOURCE == 0)
/* FORTIFY_SOURCE disabled */
#else /* _chk macros */
#if __has_builtin(__builtin___memcpy_chk)
#define memcpy(dest, src, len) __builtin___memcpy_chk(dest, src, len, __builtin_object_size(dest, 0))
#endif
```
It is supposed to replace memory routines like memcpy, memmove, strncpy, strncat, strlcat, strlcpy, strcpy, strcat, and bcopy with special chk versions which perform additional validation when targeting …
=> Add Availability.h include to fix macOS SDK instrinsics

arch/EVM/EVMDisassembler.c
Maybe these files are irrelevant for EVM.
But they should be set to 0 for compatibility, or the fuzz target should specially handle this case and not try to print the read and write registers.
=> EVM initialize regs_read and regs_write

include/capstone/mips.h
for CS_MODE_MIPS32R6
With `(cs_mode)(CS_MODE_MIPS32R6 + CS_MODE_MICRO + CS_MODE_BIG_ENDIAN)`
`21 20 d4 20` is `swm32           $s0, $s1, $s2, $s3, $s4, $s5, $s6, $fp, 0x420($zero)`
`23 20 5e 20` is `lwm32           $s0, $s1, $s2, $s3, $s4, $s5, $s6, $fp, $ra, -0x1e0($zero)`
They have 9 and 10 operands (instead of 8 previous limit)
=> Extends Mips number of operands

arch/AArch64/AArch64Module.c, arch/AArch64/AArch64Module.h, arch/ARM/ARMModule.c, arch/ARM/ARMModule.h, arch/Mips/MipsModule.c, arch/Mips/MipsModule.h, arch/PowerPC/PPCModule.c, arch/PowerPC/PPCModule.h, arch/Sparc/SparcModule.c, arch/Sparc/SparcModule.h, arch/SystemZ/SystemZModule.c, arch/SystemZ/SystemZModule.h, arch/X86/X86Module.c, arch/X86/X86Module.h, arch/XCore/XCoreModule.c, arch/XCore/XCoreModule.h, cs.c
Declare global arch arrays with contents.
This eliminates the need for archs_enable() and eliminates the racey
initialization.
Fixes #1168.
Progress:
=> Eliminates run-time initialization of global variables (fixes race condition)

arch/AArch64/AArch64Disassembler.c, arch/AArch64/AArch64Module.c, arch/AArch64/AArch64Module.h, arch/ARM/ARMDisassembler.c, arch/ARM/ARMModule.c, arch/ARM/ARMModule.h, arch/EVM/EVMModule.c, arch/EVM/EVMModule.h, arch/M680X/M680XModule.c, arch/M680X/M680XModule.h, arch/M68K/M68KModule.c, arch/M68K/M68KModule.h, arch/Mips/MipsDisassembler.c, arch/Mips/MipsModule.c, arch/Mips/MipsModule.h, arch/PowerPC/PPCDisassembler.c, arch/PowerPC/PPCModule.c, arch/PowerPC/PPCModule.h, arch/Sparc/SparcModule.c, arch/Sparc/SparcModule.h, arch/SystemZ/SystemZModule.c, arch/SystemZ/SystemZModule.h, arch/TMS320C64x/TMS320C64xModule.c, arch/TMS320C64x/TMS320C64xModule.h, arch/X86/X86Module.c, arch/X86/X86Module.h, arch/XCore/XCoreModule.c, arch/XCore/XCoreModule.h, cs.c, cs_priv.h
This eliminates the need for archs_enable() and eliminates the racey
initialization.
This makes the architecture-specific init and option functions
non-static so that they may be called from a different file.
Cherry-picked 853a2870 (from master).
Handles #1168 
Todo:
=> Declare global arch arrays with contents (next branch)

bindings/python/capstone/__init__.py
To diagnose issue with oss-fuzz building corpus
see https://github.com/google/oss-fuzz/pull/1548
Now we get the following error on oss-fuzz
```
Step #4: + ./test_corpus.py
Step #4: Traceback (most recent call last):
Step #4:   File "./test_corpus.py", line 5, in <module>
Step #4:     from capstone import *
Step #4:   File "build/bdist.linux-x86_64/egg/capstone/__init__.py", line 252, in <module>
Step #4: ImportError: ERROR: fail to load the dynamic library.
```
And I think this is not because of a missing file
=> Better error reporting for python binding

arch/X86/X86DisassemblerDecoder.c
Found by oss-fuzz with newly set memory sanitizer
Reproducing sample is `666220`
`insn->necessaryPrefixLocation` is used with `isPrefixAtLocation(insn, 0x66, insn->necessaryPrefixLocation)` but not initialized before
Patch initializes it to a value that should never match in `isPrefixAtLocation`
=> Initialize X86 necessaryPrefixLocation

arch/X86/X86DisassemblerDecoder.h
Found by os-fuzz
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=9167
The fix is to put the field `immediateOffset` in the first fields : those which are set to zero
=> Initializes to 0 X86 immediateOffset

arch/X86/X86DisassemblerDecoder.c
instructions were wrongly marked as having displacement
=> readDisplacement fix

arch/AArch64/AArch64Disassembler.c, arch/ARM/ARMDisassembler.c, arch/EVM/EVMDisassembler.c, arch/M680X/M680XDisassembler.c, arch/M68K/M68KDisassembler.c, arch/Mips/MipsDisassembler.c, arch/PowerPC/PPCDisassembler.c, arch/Sparc/SparcDisassembler.c, arch/SystemZ/SystemZDisassembler.c, arch/TMS320C64x/TMS320C64xDisassembler.c, arch/XCore/XCoreDisassembler.c, include/capstone/capstone.h
As @aquynh requested in #1125
M68K and M680X use a private struct and did not initialize cs_detail, there might be a performance penalty for those arch (but I feel it is still better to initialize structs).
=> Init cs_detail

arch/AArch64/AArch64Disassembler.c
should fix https://github.com/aquynh/capstone/issues/1144
tested using radare2 test suite, in which there's already a test for this issue
=> arm64: Fix TestAndBranch sign extend

bindings/Makefile, bindings/java/Makefile, bindings/ocaml/Makefile, bindings/python/Makefile
**Objective:**
Introduce PYTHON2 and PYTHON3 variables in the makefiles.
This change makes it possible to be explicit during the build time
on what python version/binary use to compile.
By default the same binaries should be used as now - "python" for the python 2 and "pyhon3" for version 3 of python.
**Rationale:**
In future versions of Fedora (and quite possibly other distros as well) the "python" binary will no longer be version 2 of python, but it might disappear or be replaced by python3 - most probably configurable by the particular user. Introducing the PYTHON2 and PYTHON3 variables in the makefiles makes it possible to be explicit about what version/binary of python use during the build of capstone.
For example on RHEL7:
make PYTHON2=/usr/bin/python2 PYTHON3=/usr/bin/python34 all
=> introduce PYTHON2 and PYTHON3 variables in the makefiles

arch/X86/X86ATTInstPrinter.c, arch/X86/X86IntelInstPrinter.c
The `n` parameter should be the size of the destination buffer, not the
source one.
=> arch/X86: fix strncpy usage

arch/Sparc/SparcInstPrinter.c
Fix the -Wstringop-overflow warning on GCC, similar to #1243
The last argument should be the max size of the destination, not the
source buffer. A null byte is added to the end of the destination buffer
since `strncpy` only adds one if it does not truncate the source.
=> Correct use of strncpy function

include/capstone/capstone.h
This converts various documentation comments to use Doxygen-style
syntax so that other tools can pick up and process these comments.
=> Use doxygen style comments.

include/capstone/arm.h, include/capstone/arm64.h, include/capstone/evm.h, include/capstone/m680x.h, include/capstone/m68k.h, include/capstone/mips.h, include/capstone/ppc.h, include/capstone/sparc.h, include/capstone/systemz.h, include/capstone/tms320c64x.h, include/capstone/x86.h, include/capstone/xcore.h
This is following up on #1249.
=> Adjust comments in arch headers for doxygen style.

arch/X86/X86MappingInsnOp.inc
Correct register access flag for the movdqa instruction
=> Correct register access flag for movdqa

capstone.pc.in
The include path used in the pkg-config template was missing the last path component. In fact the header are under `<install_prefix>/include/capstone` and not `<install_prefix>/include`
=> fix include path in pkg-config template

arch/X86/X86Mapping.c
Fixed minor typo, i.e. the friendly string representation of X86_REG_ST0 was "st(0"
=> Typo in a register's name

arch/X86/X86MappingInsnOp.inc
Fix registry access mode mapping for movbe16mr, movbe32mr and movbe64mr
=> Fix a few registry access mode mappings

Makefile
Uninstall was prepending `$(DESTDIR)` twice to libdir:
```Makefile
LIBDIR = $(DESTDIR)$(PREFIX)/$(LIBDIRARCH)
...
uninstall:
...
rm -f $(DESTDIR)$(LIBDIR)/lib$(LIBNAME).*
```
The change drops prefixing on `uninstall` site.
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>
=> Makefile: fix 'make uninstall DESTDIR=foo' for #1311

ChangeLog, arch/ARM/ARMInstPrinter.c, include/capstone/arm.h
For a more detailed description, see issue #1317.
Release 4.0.0 introduced a new field for ARM operands: `operand.mem.lshift`. This field was supposed to be a bug fix for #246. The #246 issue has been fixed in the meantime and the proper shift value was stored in `operand.shift.value`.
The 4.0.0 changes created a regression in which `operand.shift.value` was not set for a `tbh [r0, r1, lsl #1]` instruction on ARM and the value was set in a `operand.mem.lshift` field instead.
As the regression broke some of users codebase (e.g. in [manticore](trailofbits/manticore#1312) project), we fix it by setting `operand.shift.value` back again.
As a result, the shift value is set in two fields: `operand.shift.value` and `operand.mem.lshift`.
As the `operand.shift` also stores a `.type` field, we …
=> Fix arm thb instruction shift value

arch/MOS65XX/MOS65XXDisassembler.c
=> Add default case in MOS65XX instruction length helper

bindings/python/setup.py
=> bindings/python: fix install error due to old libname

Makefile
Commit 0a39b785d3 fixed the pkg-config include path when using cmake.
However it didn't fix it for the Makefile.  This fixes the Makefile
path.
Signed-off-by: Richard W.M. Jones <rjones@redhat.com>
=> Fix include path in pkg-config for Makefile too (#1339).

Makefile, make.sh
Fix issue when run ./make ios
error: Unsupported architecture #1170
=> make.sh: fix ./make.sh ios issue

Makefile, suite/fuzz/driverbin.c
Following https://github.com/aquynh/capstone/pull/1360#issuecomment-460014924
Is it ok to use `fuzz_bindisasm.log` as a temporary result file ?
=> Outputs in travis the offending case from corpus

tests/test_x86.c
Since the eflags and fpu_flags are union the instruction group needs
to be checked for FPU to see if the flag is an FPU flag. cstool_x86
was already doing this but test_x86 was not. The result was the fadd
instruction from the x86  16bit test was showing in the test_x86
output as having eflags. Since fadd is an fpu instruction the FPU_FLAGS
should be shown instead.
=> Print EFLAGS and FPU_FLAGS correctly in test_x86

arch/TMS320C64x/TMS320C64xInstPrinter.c
Fixes https://github.com/aquynh/capstone/issues/1366
This bug is caused by the incomplete refactor in
https://github.com/aquynh/capstone/commit/290828fc31df2ef60edd489df40af895907bae21#diff-c4736ee38f19ddccf2c25119ef7abf24.
=> Fixed TMS320C64x failed to print instructions

suite/fuzz/fuzz_disasm.c
Using only flags from capstone.h
oss-fuzz was compiling the fuzz targets without being aware of the CAPSTONE_HAS_WASM flags
See #1360
=> Fuzzing the new architectures

SStream.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12988
vsnprintf may return more characters than the buffer size
So we must check for overflow...
Finally WASM has made up a disassembly more than 512 characters long...
=> Avoid overflow in SStream.c

arch/TMS320C64x/TMS320C64xDisassembler.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12962
Left shift of a signed value is undefined behavior.
Other solution would be casting to a `uint32_t`
=> Multiply signed integer instead of left shift

suite/test_corpus.py
Oss-fuzz could not build the latest capstone because it could not build the corpus with new examples in cs test files such as `// 0xd2,0xfa,0x13,0xf1 = qsub16 r1, r2, r3`
=> Updates test_corpus to support new examples

arch/TMS320C64x/TMS320C64xDisassembler.c, arch/TMS320C64x/TMS320C64xGenAsmWriter.inc
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12957
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=12965
Maybe the best fix is to avoid calling `getRegisterName` with an invalid register as is done with the other architectures, using the result from `MCOperand_getReg` as an input to `getRegisterName`
=> Avoids overflow in getRegisterName for TMS320C64x

bindings/python/capstone/__init__.py
This leads to stable segfault on Mac.
Did not notice any issues on Linux but they still can happen.
This should finally fix #1316.
=> Fix skipdata struct being destroyed

HACK.TXT, cs.c, suite/capstone_get_setup.c, tests/test_basic.c
wasm should lay behind mos65xx (otherwise `cs_arch_disallowed_mode_mask` and `cs_arch_option` have wrong value)
also adds `suite/capstone_get_setup.c` to HACK.TXT
=> wasm: fix misordering in cs.c

arch/M68K/M68KDisassembler.c, arch/M68K/M68KInstPrinter.c, tests/test_m68k.c
Fixes #1406 
Also fixes a small type in the licensing text.
=> [M68K] store correct register value in op.reg_pair

arch/M680X/M680XDisassembler.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13487
Either the union is `int32_t imm` or it is `m680x_op_ext ext`
But it cannot be both at the same time
=> Avoids type confusion in cpu12 for M680X

arch/X86/X86ATTInstPrinter.c, arch/X86/X86IntelInstPrinter.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13466
What about `X86_BNDCL32rr` and such ? Should they be added too ?
Or is the fix for 13467 supposed to work for this one too ?
=> Fixes uninitialized memory for X86 BND instructions

suite/test_corpus.py
This should fix oss-fuzz build
(Line `// issues` in suite/MC/RISCV/insn-riscv32.s.cs was interpreted as sample hex data)
=> Corpus generation is more robust

arch/AArch64/AArch64MappingInsnOp.inc
This patch fixes the register access flags for AArch64 memory instructions, in addition to the general-purpose register ORR instruction.
Fixes #1422
=> AArch64: Fix register access flags for memory instructions

arch/ARM/ARMGenInstrInfo.inc, arch/ARM/ARMMappingInsn.inc, arch/ARM/ARMMappingInsnOp.inc
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=13768
I am not sure if I filled it correctly and completely but there is info missing for this new ARM instruction
=> Adds info for ARM brkdiv0

arch/M680X/M680XDisassembler.c
- Bug exists since adding M680X
- To save binary memory space the instruction decoding tables
are realized as struct bit-fields.
On MSVC when using enum values as a bit-field in a struct they are
interpreted as signed values => out-of-bounds array access.
- On gcc they are interpreted as unsigned values => no error.
- Fix: in the struct bit-field only use signed int and bool.
This conforms to C99.
=> Fix #1412: test_m680x crashes on Windows

contrib/riscv_update/0010-fix-riscvgenasmwiter.inc-memory-leak.patch
related to [#1424](https://github.com/aquynh/capstone/pull/1424) from @ catenacyber
=> add TableGen patch whcih fix riscv asmwrter.inc memory leak

arch/M680X/M680XDisassembler.c
- Avoid address increment by pass-by-pointer parameter.
- Code cleanup: single responsibility where and who
calculates the instruction byte size.
=> Fix coverity bug #1166

arch/M680X/M680XInstPrinter.c
- This occurs for M6809/HD6309/CPU12 PC relative indexed addressing.
In this case the register is referenced as pcr (and not pc).
- This is a consequence of lowercase registers introduced in
cc8da331d36ae6f6565057d467bc829bc3316317
- Example: lda   $FD00,pcr (instead of lda   $FD00,pcR)
=> M680X: nit: Also use lowercase 'pcr'

msvc/capstone_dll/capstone_dll.vcxproj, msvc/capstone_static/capstone_static.vcxproj, msvc/cstool/cstool.vcxproj
- Add archs BPF, EVM, M680X, RISCV and WASM to
capstone_dll, capstone_static and cstool projects.
- Add getopt.c to cstool project.
- Add X86InstPrinterCommon.c to capstone_dll
and capstone_static project.
=> msvc: Bugfix for compile errors.

arch/MOS65XX/MOS65XXDisassembler.c
Changed style according to https://github.com/aquynh/capstone/pull/1439
Signed-off-by: Sebastian Macke <sebastian@macke.de>
=> MOS65XX: Use same output style as other archs

arch/TMS320C64x/TMS320C64xInstPrinter.c
Fixes #1418
`TMS320C64x_post_printer()` added `"|||||"` to the beginning of the mnemonic.
`fill_insn()` replaced `'|'` with `' '`, which caused the extra whitespace.
Someone more familiar with tms320c64x should make sure this makes sense.
=> tms320c64x: remove extra indent

bindings/python/capstone/__init__.py
I'm not very familiar with the capstone code but surely it would be better to pass bytearrays by reference instead of making a copy using `bytes`? This can be done by passing the bytearray to  `from_buffer` on the relevant ctype.
=> Python binding handling of bytearrays

suite/fuzz/platform.c
Separate PR as requested in #1470
=> Right endianness for ppc platforms

contrib/windows_kernel/libc.cpp, windows/winkernel_mm.c
Kernel memory allocations on Windows should be aligned on `MEMORY_ALLOCATION_ALIGNMENT` (16 bytes on x64 and 8 bytes on x86).
=> Fix user data alignment in MEMBLOCK

arch/X86/X86MappingInsnOp.inc, arch/X86/X86MappingInsnOp_reduce.inc
This PR fixes the access mode of the memory operand for variants of `call` and `jmp` instructions. Currently, this access mode is set to `CS_AC_IGNORE`. The fixed mode is `CS_AC_READ`
In order to check the fix, I provide sample hex code of instructions `jmp	qword ptr [rax*8 + 0x4edbe0]` and `call	qword ptr [rax*8 + 0x4edbe0]` respectively. 
```
cstool -d x64 "ff 24 c5 e0 db 4e 00"
```
```
cstool -d x64 "ff 14 c5 e0 db 4e 00"
```
=> x86: fix call/jmp access mode of mem operand

COMPILE.TXT, arch/M680X/M680XDisassembler.c, arch/M680X/M680XInstPrinter.c, cs_priv.h
- This is not suitable for an application framework
especially for kernel code.
- All these error conditions do not occur under normal conditions.
They only can occur if a maintainer (in the future) would make
inappropriate changes to the M680X code base.
- Added CS_ASSERT macro which allows to use assertions when debugging.
=> [M680X] Fix #1483: errors logged to stderr, using abort (2)

arch/MOS65XX/MOS65XXDisassembler.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=15112
Test example is
`cstool -d 6502 "30 20"`
Expected output is 
```
Groups: jump branch_relative 
```
instead of
```
Groups: branch_relative (null)
```
=> Fixes MOS groups count

suite/synctools/tablegen/PPC/PPCInstrHTM.td, suite/synctools/tablegen/PPC/PPCInstrInfo.td, suite/synctools/tablegen/PPC/PPCRegisterInfo.td
Following #1478 
Patch is now approved on LLVM : https://reviews.llvm.org/D61935
There is still sync tools to run
LLVM updated more than just `tbegin` and such instructions. So I do not know if you want these or not....
=> Updates files from LLVM for PPC64

bindings/java/capstone/Capstone.java
Previously, a long was used instead of a pointer in the JNA binding library.
This would work until the allocated pointers exceeded 32-bits. On modern JVMs,
allocations may produce pointers in excess of 32-bits which would result in
invalid memory access errors.
This also updates the binding version to 5.0.
=> #1246 - Fix Java bindings to use pointers instead of longs

.gitignore, Makefile, make.sh
1. According to the issue #1518, I made a fix for the broken Android compilation script;
2. The fix is based on building standalone Android NDK env first, as I think this is the most general way for old & new version NDK, see this [link](https://developer.android.com/ndk/guides/other_build_systems?hl=zh-CN) for more details;
3. I replace the gcc to clang as Android has no support for gcc now;
4. You can try `NDK=/path/to/the/unzipped/ndk/dir ./make.sh cross-android arm64 [clean]` to test it. The build process is well but there is a problem for `make test`, the failure is because of the lack of `bingcc`:
```bash
make -C tests
make[1]: Entering directory '/root/workspace/capstone_make/capstone/tests'
/bin/sh: 1: /root/workspace/capstone_make/capstone/android-ndk-arm64-android-21/aarch64-linu …
```
=> fix for make.sh for android

Makefile, cstool/Makefile, functions.mk, suite/fuzz/Makefile, tests/Makefile
Hi, I've fixed 47 missing dependencies and 51 excessive dependencies reported.
Those issues can cause incorrect results or unnecessary rebuilds when capstone is incrementally built.
For example, any changes in "arch/AArch64/AArch64BaseInfo.h" will not cause "arch/AArch64/AArch64BaseInfo.o" to be rebuilt, which is incorrect.
"MCInstrDesc.h" is specified as the prerequisite of "arch/Mips/MipsDisassembler.o". However, this header file is not read by the process when "arch/Mips/MipsDisassembler.o" is built. Hence, the changes in "MCInstrDesc.h" can cause an unnecessary rebuild of "arch/Mips/MipsDisassembler.o", which slow down the build of the whole project.  
A useful tool is the -M class of flags that we can pass to clang/gcc to generate "dependency files". Even if we don't use the flag …
=> Fixed 47 missing dependencies and 51 excessive dependencies in Makefile

bindings/README
See the comment from the previous Go bindings author here
https://github.com/bnagy/gapstone/pull/23#issuecomment-523719741
He is not actively maintaining the bindings anymore. I've forked it and updated it with 4.0.1 support. It would be nice to get the community going to the updated bindings.
=> Update Go binding information

bindings/ocaml/ocaml.c, bindings/ocaml/test_x86.ml
This PR fixes a bug with the `x86_op` record in the ocaml bindings. 
Before the change fields such as `size` where returned with bad values, for example:
```
Platform: X86 64 (Intel syntax)
0x1000	push	rbp
Prefix:
Opcode: 0x55
addr_size: 8
modrm: 0x0
sib: 0x0
op_count: 1
op[0]: REG = rbp  [sz=2944]
```
After the change the fields are correctly returned to ocaml:
```
Platform: X86 64 (Intel syntax)
0x1000	push	rbp
Prefix:
Opcode: 0x55
addr_size: 8
modrm: 0x0
sib: 0x0
op_count: 1
op[0]: REG = rbp  [sz=8]
```
=> Fix for x86_op record for ocaml bindings

Makefile, include/capstone/capstone.h, make.sh
These changes add support for IBM systems.
`xlc` is the compiler used, `ar` have different options on certain platforms and `ranlib` is unavailable on certain platforms
=> build: add xlc and AIX support

arch/SystemZ/SystemZInstPrinter.c
- In cases where base is 0 but index is not, Capstone doesn't print anything
=> systemz: fix base/index printing

CMakeLists.txt
Have been looking into getting the latest release build on Haiku with some changes in CMakeList.txt, however the master branch here is ahead of the release (as it should) so I checked some changes.
You already switched to CMAKE_INSTALL_LIBDIR, switching to CMAKE_INSTALL_INCLUDEDIR should fix the buid on Haiku and shouldn't harm any other OS.
=> Use GNUInstallDirs for the headers too

COMPILE.TXT
Update section 2:
- add missing mos65xx.h header
- force alphabetical order (LANG=C) of core files
Update section 4:
- remove trailing space
=> Update top-level COMPILE.TXT file

.travis.yml
For more information see [Multiarchitecture support](https://blog.travis-ci.com/2019-10-07-multi-cpu-architecture-support) and [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog posts from Travis CI.
Checking on these architectures will help eliminate endianess/portability problems in the code.
=> Add ARM64, System Z & PowerPC CI

.github/workflows/coverity-scan.yml
Since we migrated our CI, and Capstone used our CI, setting GitHub Action would help automate sending builds without our help.
You only need to add the token (you can see it at https://scan.coverity.com/projects/capstone-next/builds/new page) in the Github repo Settings -> Secrets -> Add
There you should add a token with a name `COVERITY_SCAN_TOKEN`
Feel free to reach me if you have questions.
=> Add Coverity Scan Action

arch/ARM/ARMMappingInsnOp.inc
Fix issue #1587 
New output is:
```
./cstool -d thumb 2DE9F047
0  2d e9 f0 47  push.w {r4, r5, r6, r7, r8, sb, sl, lr}
ID: 128 (push)
op_count: 8
operands[0].type: REG = r4
operands[0].access: READ
operands[1].type: REG = r5
operands[1].access: READ
operands[2].type: REG = r6
operands[2].access: READ
operands[3].type: REG = r7
operands[3].access: READ
operands[4].type: REG = r8
operands[4].access: READ
operands[5].type: REG = sb
operands[5].access: READ
operands[6].type: REG = sl
operands[6].access: READ
operands[7].type: REG = lr
operands[7].access: READ
Registers read: sp r4 r5 r6 r7 r8 sb sl lr
Registers modified: sp
Groups: thumb2
```
=> fix: Remove wrong write in ARM_t2STMDB_UPD instruction

arch/X86/X86Mapping.c
Solve the issue #1538 (SSE variant of MOVSD is incorrectly decoded as REPNE MOVSD)
=> Bug solved: #1538

.github/workflows/fuzz.yml
OSS-Fuzz was wondering if capstone would use CIFuzz, a new feature being rolled out 
in OSS-Fuzz. It allows for pull requests to be fuzzed in CI using fuzz targets enabled 
in OSS-Fuzz. Documentation for this feature can be found [here](https://google.github.io/oss-fuzz/getting-started/continuous-integration/). 
Let us know if you have any questions!
=> Add CIFuzz action

bindings/README
Add my fork of Crabstone (Ruby binding of Capstone) to bindings/README, which supports both Capstone 3 & 4.
=> Add Ruby binding by david942j

include/capstone/m68k.h
Apple Clang 11.0.0 error:
```
capstone/include/capstone/m68k.h:160:3: error: anonymous types declared in an anonymous union are an extension [-Werror,-Wnested-anon-types]
struct {                    ///< register pair in one operand
^
```
=> Fixed anonymous type in anonymous union error in m68k.h

COMPILE_MSVC.TXT
`capstone`  is available as a port in [vcpkg](https://github.com/microsoft/vcpkg/tree/master), a C++ library manager that simplifies installation for `capstone`  and other project dependencies. Documenting the install process here will help users get started by providing a single set of commands to build `capstone` , ready to be included in their projects.
We also test whether our library ports build in various configurations (dynamic, static) on various platforms (OSX, Linux, Windows: x86, x64, UWP, ARM) to keep a wide coverage for users.
I'm a maintainer for vcpkg, and [here is what the port script looks like](https://github.com/microsoft/vcpkg/blob/master/ports/capstone/portfile.cmake). We try to keep the library maintained as close as possible to the original library.
=> Add vcpkg installation instructions

arch/AArch64/AArch64InstPrinter.c
=> aarch64: Add more cases for LD1 instruction immediate fixups

arch/X86/X86DisassemblerDecoder.c
This solves https://github.com/aquynh/capstone/issues/1560
The removed line was making Line 1402 effectively dead code.
=> fix bug in displacement offset

bindings/Makefile, bindings/java/Makefile, bindings/ocaml/Makefile, bindings/python/Makefile
`$(PYTHON2)` and/or `$(PYTHON3)` might differ from `python` and/or `python3`,
accordingly. Allow to override these variables by user choice.
=> Allow to override PYTHON[23] in Makefiles

CMakeLists.txt, capstone-config.cmake.in
Generates a few more files on install to add support for cmake's [find_package](https://cmake.org/cmake/help/latest/command/find_package.html) system, thereby simplifying the use of capstone in cmake projects, for instance:
```cmake
cmake_minimum_required(VERSION 3.0)
project(test)
find_package(capstone CONFIG REQUIRED)
add_executable(main main.cpp)
target_link_libraries(main PRIVATE capstone::capstone-static)
```
Also see [CMakePackageConfigHelpers](https://cmake.org/cmake/help/latest/module/CMakePackageConfigHelpers.html). Tested with Visual Studio 2019 and CMake 3.17 using the following code for `main.cpp`:
```c++
#include <capstone/capstone.h>
#include <stdio.h>
int main()
{
int major = -1, minor = -1;
cs_version(&major, &minor);
printf("capstone version %i.%i\n", major, minor); …
```
=> Add cmake config and export targets.

arch/M68K/M68KDisassembler.c
This is a fix for https://github.com/aquynh/capstone/issues/1643
=> Fixed incorrect read of 32-bit imm for bsr

include/capstone/riscv.h
Fixed a build issue. I integrate the capstone directory into a larger project and use the cmakefile. It was an easy fix, but not sure how I can show how to reproduce in your git repo.
```
In file included from /home/mjm/sim/src/capstone/include/capstone/capstone.h:302,
from /home/mjm/sim/src/ampere/event_stream/event_stream.cc:22:
/home/mjm/sim/src/capstone/include/capstone/riscv.h:16:10: fatal error: capstone/platform.h: No such file or directory
#include "capstone/platform.h"
^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
=> Change include path to fix error with embedded cmake builds

capstone.pc.in
On x86_64-linux gentoo system capstone was installing
it's files to 'lib64' libdir, but was referring 'lib' libdir:
```
$ cat /usr/lib64/pkgconfig/capstone.pc
...
libdir=${prefix}/lib
...
```
On radare2 built it means injecting -L/usr/lib into a 64-build
and pulling in 32-bit libraries. 'ld.lld' is not able to resolve
the ambiguity.
It happens because @LIBSUFFIX@ is not present in cmake-3.17.3.
Let's fix the paths by using @CMAKE_INSTALL_LIBDIR@.
This variable is already used in capstone's build system,
thus should be safe to rely on.
Reported-by: Agostino Sarubbo
Bug: https://bugs.gentoo.org/730722
=> capstone.pc.in: use CMAKE_INSTALL_LIBDIR for libdir

cstool/cstool.c
instructions could be 2, 4 or 6 bytes so pad accordingly as it
was done on the other CISC architecture.
=> systemz: pad instruction width up to 6 bytes

include/capstone/capstone.h
if integer is 32-bit, and numeric literals default to int type,
the following applies (from The C Standard, 6.5.7, paragraph 4
[ISO/IEC 9899:2011]):
If E1 has a signed type and nonnegative value, and E1 × 2^E2 is
representable in the result type, then that is the resulting value;
otherwise, the behavior is undefined.
which means that the only way to safely shift is unsigned, so
use 1U to indicate the shifted bit is unsigned.
=> include: avoid UB with signed overflow/shift

arch/RISCV/RISCVDisassembler.c, cs.c
The first patch is a cleaner version of pulll #1594, which I discovered after writing the patch.
The second patch is a small fix for skipdata.
=> Two RISC-V fixes

MCInst.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14912
Same as https://github.com/aquynh/capstone/pull/1684 for next branch
=> MCInst: fix uninitialized value in operand value (next)

CMakeLists.txt
For projects that embed Capstone and have their own installer, prevent Capstone from installing as well for the ALL target.
=> Option to generate install target

arch/M680X/M680XDisassembler.c
If you compile capstone with `-Werror` warning enabled it produces the following error:
```
CC      arch/M680X/M680XDisassembler.o
arch/M680X/M680XDisassembler.c:2124:20: error: variable 's_cpu_type' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
static const char *s_cpu_type[] = {
^
1 error generated.
```
Since `s_cpu_type` is not used anywhere in the `next` branch, it's safe to just remove it completely. It was used in the `master` branch only, albeit also unnecessary.
cc @trufae @ret2libc
=> M680X - remove unused s_cpu_type

.github/workflows/python-publish.yml, CREDITS.TXT, bindings/python/build_wheel.sh, bindings/python/setup.cfg, bindings/python/setup.py
**Purpose:**
- Utilizing github action to build and publish python distribution packages including source package to pypi.org on repo [tag]. Build will still be triggered on [push].
- Speed up project release process.
**Binary distribution packages:**
sdist, win32, win-amd64, manylinux1_x86_64, manylinux1_i686, macos_10.14_x86_64
**Preparation:**
- Go to https://pypi.org/manage/account/#api-tokens and create a new API token for the Capstone-engine project on PyPI, limit the token scope to just this project. You can call it something like GitHub Actions CI/CD or anything that can be easily distinguishable in the token list. Don’t close the page just yet — you won’t see that token again.
- In a separate browser tab or window, go to the Github Settings tab of capstone-engine/capstone …
=> PyPI workflow

bindings/python/setup.py
Otherwise python setup.py install from bindings/python
will fail with
SyntaxError: Non-ASCII character '\xe2' in file setup.py on line 223,
but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Should fix oss-fuzz build
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=27542
=> python: only use ascii character

bindings/README, bindings/const_generator.py
I've been working on a Capstone binding for Swift: [capstone-swift](https://github.com/zydeco/capstone-swift).
Due to how Swift packages work, it must be in its own repository.
This required some additions to the const generator script to map constants in a more swift-like way:
* Export related constants as an enum or OptionSet
* Rename using Swift naming conventions
* Swift enum values must be literals
These changes don't affect other bindings, but if it's inconvenient to have so much code in the const generator script only for Swift, I can keep it in my own repo.
=> Swift binding

arch/M68K/M68KDisassembler.c
This commit fixes #1708 with fmove opcode.
=> M68k: Honour direction bit in fmove instruction

bindings/python/setup.py
It looks like `manylinux1` does not seem to support aarch64 architectures (see [the manylinux README](https://github.com/pypa/manylinux#manylinux1)). I'm getting this error when trying to install the wheel with `pip`:
```
ERROR: capstone-4.0.2-py3-none-manylinux1_aarch64.whl is not a supported wheel on this platform.
```
According to [PEP 599](https://www.python.org/dev/peps/pep-0599/#backwards-compatibility-with-manylinux2010-wheels) it seems like `manylinux2014` is what should be used instead.
Here are logs from our failing build (in NixOS): https://hydra.nixos.org/build/134963890/nixlog/1/tail
=> add support for aarch64 distributions

arch/X86/X86Mapping.c
In https://github.com/aquynh/capstone/commit/0932f167fd5620bba1619fc3fae90924292ebb2e a fix was submitted to remove the repne/repnz prefix from movs instructions with SSE registers. However, the change checks for X86_MOVSW rather than X86_MOVSL (movsd).
This breaks a simple repne movsd instruction:
want:
0:  f2 a5                   repnz movs DWORD PTR es:[edi],DWORD PTR ds:[esi]
got:
0:  f2 a5                   movs DWORD PTR es:[edi],DWORD PTR ds:[esi]
Clearly, the f2 prefix is dropped, even though it should be present.
=> Fix bug introduced in commit 0932f167fd5620bba1619fc3fae90924292ebb2e

bindings/python/capstone/__init__.py
When there are regs returned they are in a list, so the function returns a tuple of 2 lists.
When there are no regs, a tuple is returned instead, so it will be a tuple of tuples (or a tuple of one tuple + one list).
=> Always return the same type from regs_read

cs.c
When setting up skipdata with the mnemonic as `NULL`, capstone will crash during disassembly here when trying to strcpy a null pointer:
https://github.com/aquynh/capstone/blob/c93fa3a79614a0de48dcb0b9dd98156bd6326bee/cs.c#L945-L946
This can be verified by changing `cs_opt_skipdata` in `test_skipdata.c`.
This fix will use the `SKIPDATA_MNEM ` constant when `NULL` is passed, so it will work according to the documentation:
https://github.com/aquynh/capstone/blob/c93fa3a79614a0de48dcb0b9dd98156bd6326bee/include/capstone/capstone.h#L255-L260
=> fix crash when using skipdata with NULL mnemonic

arch/PowerPC/PPCDisassembler.c
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236
Same as https://github.com/aquynh/capstone/pull/1687 for next branch
=> ppc: fix registers overflow (next)

cs.c
This commit fixes these two warnings:
```
cs.c: In function ‘cs_option’:
393
cs.c:710:4: error: this ‘if’ clause does not guard... [-Werror=misleading-indentation]
394
710 |    if (value)
395
|    ^~
396
cs.c:712:5: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
397
712 |     if (handle->skipdata_setup.mnemonic == NULL)
398
|     ^~
```
=> Fix pythonic bug

bindings/python/setup.py
With FreeBSD, OpenBSD, NetBSD verified we can simply use "bsd".
Signed-off-by: Tomasz 'CeDeROM' CEDRO <tomek@cedro.info>
=> Enable detection and build on all BSD systems.

README.md
This corrected a small typo in the README.md
=> Fixed a small typo `Mac OSX`

arch/X86/X86DisassemblerDecoder.c
This was initially introduced in dce7da9 but lost in the LLVM 7 sync
in 5a99624.
=> Fix the displacement offset for moffset-encoded operands

bindings/python/capstone/__init__.py, bindings/python/test_basic.py
Recreation of https://github.com/aquynh/capstone/pull/1758 relative to the `next` branch.
=> support disassembling bytes from memoryview

arch/AArch64/AArch64InstPrinter.c
This pr fixes #1653 
I noticed that the problem relies on the fact that `cmp x0, x1` is in fact alias for `subs xzr, x0, x1`.
Now, when the method `printAliasInstruction` calls `printOperand`, it passes the correct operand number (skips the first register xzr, and asks for x0); however `printOperand` then uses `MI->ac_idx` to address which reg access information to return back - and this is wrong, as MI->ac_idx is initialized with 0 and it should use the proper `OpNum` argument that is passed to `printOperand`
IMHO `MI->ac_idx` is an artifact from arm32 that got carried over to the arm64 implementation, and as we don't need to deal with multiple register edge cases like `pop {r1,r2,r3,r4...}`  I don't see the need for `MI->ac_idx` at all for arch64, but I am probably wrong (this is my …
=> Fix cmp register access on aarch64

arch/M680X/M680XDisassembler.c
This pr cherry-picks c93fa3a79614a0de48dcb0b9dd98156bd6326bee (#1695) from `next` into `v4` to fix the following warning:
(https://github.com/rizinorg/rizin/runs/4351274434?check_suite_focus=true#step:12:697)
=> M680X - remove unused s_cpu_type (#1695)

.github/workflows/build_release.yml
after a tag is pushed, and "create release from tag" is clicked, CI
will now create an xz-compressed release tarball, containing all sources
and submodules (if used).
closes #582
result can be seen here: https://github.com/rofl0r/capstone/releases/tag/9.99.99a
=> CI: automatically build release tarball

arch/AArch64/AArch64GenAsmWriter.inc, arch/AArch64/AArch64InstPrinter.c
Hello,
I have found a few regressions and issues while updating the Capstone library that I'm using in my project.
- The first one is related to the `vess` ARM64 field which was merged with the `vas` field. Some instructions were missing the correct VAS information,
- The second issue is a missing writeback information on two ARMv8.3 instructions (`LDRAA` and `LDRAB`),
- The last issue seems to be a copy and paste issue in the `printGPRSeqPairsClassOperand` method which was using the vector-related register mapping function `AArch64_map_vregister`.
=> Fixes a few issues

cs.c
This was causing a build failure when considering warnings as errors, this is a good practice and should be checked in the CI
reference link https://github.com/radareorg/radare2/runs/4730735642?check_suite_focus=true
=> Fix warning about Unused variables

tests/test_customized_mnem.c
if the library is built without X86, then cs_open() should fail
but that shouldn't be treated as an error, so return instead after
checking.
=> test_customized_mnem: avoid abort() if x86 not supported

suite/synctools/tablegen/X86/X86InstrControl.td, suite/synctools/tablegen/X86/back/X86InstrControl.td
I found that lcall seg:off is wrongly printed for x86-16.
```
$ ./cstool x16 9a0d000000
0  9a 0d 00 00 00                                   lcall	0, 0xd
```
for example ljmp is correct:
```
$ ./cstool x16 ea0d000000
0  ea 0d 00 00 00                                   ljmp	0:0xd
```
found also that this wrong format comes from this differences (skipping uninterested lines from grep output):
```
suite/synctools/tablegen/X86$ grep -r seg | grep lcall
X86InstrControl.td:                               "lcall{w}\t$seg, $off", []>,
X86InstrControl.td:                               "lcall{l}\t$seg, $off", []>,
back/X86InstrControl.td:                               "lcall{w}\t$seg, $off", []>,
back/X86InstrControl.td:                               "lcall{l}\t$seg, $off", []>, …
```
=> fix lcall seg:off format for x86-16

Makefile, capstone.pc.in
Usage:
$ pkg-config --variable=archs capstone
arm aarch64 m68k mips powerpc sparc systemz x86
xcore tms320c64x m680x evm riscv mos65xx wasm bpf
=> Add the archs variable in the pkg-config file

arch/X86/X86GenAsmWriter1.inc
This reverts commit e4965783cfb30c12ae8f1b7bbce446fef03e2b68.
=> Revert "x86: fix lcall seg:off format for x86-16 (#1827)"

CMakeLists.txt, bindings/python/setup.py, bindings/python/setup_cython.py
Closes #1826
This refactors capstone's CMake to be compatible with both `find_package` and `FetchContent`. You can build capstone like this:
```sh
cmake -B build -DBUILD_SHARED_LIBS=OFF # or whatever options you want
cmake --build build
cmake --install build --prefix build/install
```
Then in your project's `CMakeLists.txt`:
```cmake
find_package(capstone REQUIRED)
add_executable(my_tool src/main.cpp)
target_link_libraries(my_tool PRIVATE capstone::capstone)
```
And to build you point `CMAKE_PREFIX_PATH` to the `build/install` you just created:
```sh
cmake -B build -DCMAKE_PREFIX_PATH=/path/to/capstone/build/install
```
Or alternatively you can use `FetchContent`:
```cmake
include(FetchContent)
message(STATUS "Fetching capstone (cmake-packaging)...")
FetchContent_Declare(
capstone …
```
=> Modernize CMake and switch to CMake 3.15

.github/workflows/python-publish.yml, arch/AArch64/AArch64InstPrinter.c, suite/cstest/issues.cs
Fix https://github.com/capstone-engine/capstone/issues/1839 first bug
=> fixed incorrect MI->ac_idx leading to wrong AArch64 InsnOp access printing

CMakeLists.txt
This PR fixes cases where `capstone.pc` was not installed in case `CAPSTONE_INSTALL` is set to true but `CAPSTONE_BUILD_CSTOOL` is set to false.
=> Fix pkgconfig not installed when CAPSTONE_BUILD_CSTOOL is false

arch/AArch64/AArch64InstPrinter.c, arch/AArch64/AArch64Mapping.c, suite/cstest/issues.cs, suite/cstest/src/arm64_detail.c
I attempted to comprehensively go through the ARM Architecture Reference Manual to find all the aliased instructions that should have `.vas` specifiers and fix them all.
Fixes #1873
=> AArch64 comprehensively add vas specifiers to aliased instructions

capstone.pc.in
c8172e4c107201dd8c2b4644fc73661752ac82fc dropped the CMake variables `VERSION_MAJOR`, `VERSION_MINOR` and `VERSION_PATCH` which were still in use in `capstone.pc.in`. This PR fixes the pkg-config template to reflect the current version.
=> Fix pkg-config template

cs.c, cs_priv.h
Per @trufae reported,
```
=================================================================
==251167==ERROR: AddressSanitizer: odr-violation (0x7f5cd9115f40):
[1] size=8 'cs_vsnprintf' cs.c:299:16
[2] size=8 'cs_vsnprintf' cs.c:299:16
These globals were registered at these points:
[1]:
#0 0x7f5ce2a20938 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
#1 0x7f5cd5fbc712 in _sub_I_00099_1 (/usr/local/lib/libr_anal.so+0x3260712)
#2 0x7f5ce3401b99 in call_init /build/glibc-SzIz7B/glibc-2.31/elf/dl-init.c:72
[2]:
#0 0x7f5ce2a20938 in __asan_register_globals ../../../../src/libsanitizer/asan/asan_globals.cpp:341
#1 0x7f5cde789b44 in _sub_I_00099_1 (/usr/local/lib/libr_asm.so+0x103db44)
#2 0x7f5ce3401b99 in call_init …
```
=> Mark cs_* as thread local to avoid race condition in multithreads

suite/synctools/tablegen/X86/X86InstrSystem.td
The change in this PR is to address the problem regarding UD0 and UD1: i.e., the capstone decoder was not able to process the arguments of these instructions correctly.
According to the X86 instruction-set manual, UD0 and UD1 (Undefined Instruction) take two arguments:
UD0 r32, r/m32
UD1 r32, r/m32
(https://www.felixcloutier.com/x86/ud)
It was observed that capstone does not read the bytes after the opcode correctly, and does not produce the two arguments.
At first, I tried to update all the tables in suite/synctools/tablegen/X86/ with the latest llvm tables, but I was getting various problems.
One of them was that any instructions with zmm regsiters as operands are decoded incorrectly.
After several hours of trial, I ended up giving up updating the whole tables, and instead, I tried …
=> Update the table for UD0 and UD1 with the latest llvm table

bindings/python/setup.py
The library ctypes has shipped with the python standard library since
Python 2.5, however this was still added via the `requires` keyword in
setuptools.setup. This results in a spurious requirement being created
in the .whl METADATA file, causing warnings when packaged via tools like
pex:
```
$ python3 -m pex capstone -o capstone.pex
/Users/ott/.venv/lib/python3.9/site-packages/pex/dist_metadata.py:397: PEXWarning: Ignoring 1 `Requires` field in /Users/ott/.pex/installed_wheels/2a4c7a0d4c87aceed3134ae20997a764af1811fee8e151cf5da90e0462822893/capstone-4.0.2-py3-none-macosx_12_arm64.whl metadata:
1.) Requires: ctypes
You may have issues using the 'capstone' distribution as a result.
More information on this workaround can be found here: …
```
=> Remove outdated ctypes requirement

suite/arm/test_arm_regression.c
Prevents spurious error when compiling the test suite with `-fsanitize=address`.
=> Fix memory leak in testsuite

arch/M68K/M68KDisassembler.c
FNOP is a special case of FBF which can be used for synchronization
=> m68k: Add support for the FNOP instruction

arch/AArch64/AArch64Disassembler.c, arch/AArch64/AArch64InstPrinter.c
Where new code started using `malloc()` and `free()` directly instead of
going through the cs_mem_* functions.
=> Fix regressions in custom memory allocator support

debug_build_docs
Mentioning of the flag was missing. And for people who don't use `cmake` often this might not be common knowledge.
=> Mention debug build option for cmake.

cstool/cstool.c
When a compressed opcode is printed, make sure there is enough extra space at the end of it for the instructions to align.
=> cstool: avoid misaligned instructions in compressed riscv

bindings/python/capstone/__init__.py
It seems somebody introduced `post_index` in commit 784aa0f but forgot add it in `bindings/python/capstone/__init__.py`, line 677, which causes `ValueError: too many values to unpack` exception. This pr is a small fix to correct it.
=> arm64: fix missing post_index

COMPILE_CMAKE.TXT
This adds the `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to the `cmake` build instructions. I think it is a commonly wanted option since `compile_commands.json` is used by `clangd`. So people who work on the code possibly want this.
Also this PR renames the file from `debug_build_docs` to `COMPILE_CMAKE.TXT`. Because I accidentally renamed it in the last commit.
=> Add `CMAKE_EXPORT_COMPILE_COMMANDS` to cmake build doc

arch/RISCV/RISCVDisassembler.c, arch/TMS320C64x/TMS320C64xMapping.c
(I have no experience with this code base so someone should probably review this before merging.)
=> Fix potential array out of bounds

cs.c, cs_priv.h
Having per-thread memory allocation routines is a major change in behavior that likely broke a lot of applications.
This reverts commit bdab89496e654d043f556e27a68c2ac47dd571a7.
=> Revert "Mark cs_* as thread local to avoid race condition in multithreads"
